import { Component, ElementRef, OnDestroy, OnInit, ViewChild, computed, inject, input, output, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Subscription } from 'rxjs';
import { Product } from '../../../core/models/barcode-product.model';
import { MEAL_TYPE_LABELS, MealType } from '../../../core/models/meal-plan.model';
import { BarcodeProductService } from '../../../core/services/barcode-product.service';
import { BrowserBarcodeScannerService } from '../../../core/services/barcode-scanner.service';
import { calculateNutritionForGrams, isSupportedBarcode, normalizeBarcode } from '../../../shared/utils/barcode-product.utils';

@Component({selector:'app-barcode-product-dialog',standalone:true,imports:[ReactiveFormsModule],template:`
<div class="fixed inset-0 z-50 flex items-end justify-center bg-stone-900/50 p-4 sm:items-center" role="dialog" aria-modal="true" aria-labelledby="barcode-title">
 <div class="card flex max-h-[92vh] w-full max-w-lg flex-col overflow-hidden">
  <header class="flex items-start justify-between border-b p-4"><div><h2 id="barcode-title" class="font-semibold">{{ product() ? 'Add packaged food' : 'Scan barcode' }}</h2><p class="mt-1 text-sm text-stone-600">{{ product() ? labels[mealType()] + ' · ' + date() : 'Point the rear camera at the package barcode.' }}</p></div><button type="button" class="grid h-11 w-11 place-items-center" aria-label="Close scanner" (click)="cancelled.emit()">×</button></header>
  <div class="overflow-y-auto p-4">@if(error()){<p class="alert-error mb-4" role="alert">{{error()}}</p>}@if(loading()){<p class="alert-info" role="status">Looking up product…</p>}@else if(product();as p){
   <div class="flex gap-4">@if(p.imageUrl){<img [src]="p.imageUrl" [alt]="p.name" class="h-24 w-24 rounded-xl object-contain ring-1 ring-stone-200">}<div><h3 class="text-lg font-semibold">{{p.name}}</h3><p class="text-sm text-stone-600">{{p.brand||'Brand unavailable'}}</p><p class="mt-2 text-xs text-stone-500">Open Food Facts · {{quality()}}</p></div></div>
   <form class="mt-5 grid grid-cols-2 gap-4" [formGroup]="form"><div><label for="grams" class="mb-1 block text-sm font-medium">Grams consumed</label><input id="grams" class="input" type="number" min="1" formControlName="grams"></div><div><label for="servings" class="mb-1 block text-sm font-medium">Servings</label><input id="servings" class="input" type="number" min="0.1" step="0.1" formControlName="servings"></div></form>
   <dl class="mt-5 grid grid-cols-4 gap-2 text-center">@for(n of nutrition();track n.label){<div class="rounded-xl bg-stone-50 p-2"><dt class="text-xs text-stone-500">{{n.label}}</dt><dd class="mt-1 text-sm font-semibold">{{n.value}}</dd></div>}</dl>
  }@else{<div class="relative aspect-[4/3] overflow-hidden rounded-2xl bg-stone-950"><video #video muted playsinline class="h-full w-full object-cover"></video><div class="absolute inset-[20%] rounded-xl border-2 border-white" aria-hidden="true"></div></div><form class="mt-4 flex gap-2" [formGroup]="manualForm" (ngSubmit)="lookupManual()"><label class="sr-only" for="barcode">Barcode</label><input id="barcode" class="input flex-1" inputmode="numeric" placeholder="Enter barcode manually" formControlName="barcode"><button class="btn-secondary" type="submit">Look up</button></form>@if(!scanner.isSupported()){<p class="mt-3 text-sm text-stone-600">Live scanning is unavailable here. Manual entry still works.</p>}}</div>
  <footer class="flex gap-3 border-t p-4">@if(product()){<button class="btn-secondary flex-1" type="button" (click)="scanAnother()">Scan another</button><button class="btn-primary flex-1" type="button" [disabled]="form.invalid||saving()" (click)="add()">{{saving()?'Adding…':'Add to meal plan'}}</button>}@else{<button class="btn-secondary w-full" type="button" (click)="cancelled.emit()">Cancel</button>}</footer>
 </div>
</div>`})
export class BarcodeProductDialogComponent implements OnInit,OnDestroy{
 @ViewChild('video') video?:ElementRef<HTMLVideoElement>;readonly date=input.required<string>();readonly mealType=input.required<MealType>();readonly saved=output<void>();readonly cancelled=output<void>();readonly scanner=inject(BrowserBarcodeScannerService);private products=inject(BarcodeProductService);private fb=inject(FormBuilder);private sub?:Subscription;
 readonly labels=MEAL_TYPE_LABELS;readonly product=signal<Product|null>(null);readonly loading=signal(false);readonly saving=signal(false);readonly error=signal<string|null>(null);readonly manualForm=this.fb.nonNullable.group({barcode:['',Validators.required]});readonly form=this.fb.nonNullable.group({grams:[0,[Validators.required,Validators.min(1)]],servings:[1,[Validators.required,Validators.min(.1)]]});
 readonly nutrition=computed(()=>{const p=this.product();if(!p)return[];const n=calculateNutritionForGrams(p.nutrition,this.form.controls.grams.value||1);const f=(v:number|null,u:string)=>v===null?'—':`${Math.round(v*10)/10}${u}`;return[{label:'Calories',value:f(n.calories,' kcal')},{label:'Protein',value:f(n.protein,' g')},{label:'Carbs',value:f(n.carbohydrates,' g')},{label:'Fat',value:f(n.fat,' g')}];});
 ngOnInit(){document.body.classList.add('overflow-hidden');this.sub=this.scanner.scanResults().subscribe(x=>void this.lookup(x.rawValue));setTimeout(()=>void this.start());}ngOnDestroy(){this.sub?.unsubscribe();void this.scanner.stop();document.body.classList.remove('overflow-hidden');}
 private async start(){if(!this.scanner.isSupported())return;try{if(this.video)await this.scanner.start(this.video.nativeElement);}catch(e){this.error.set(e instanceof DOMException&&e.name==='NotAllowedError'?'Camera permission was denied. Enter the barcode manually.':'Camera is unavailable. Enter the barcode manually.');}}
 lookupManual(){void this.lookup(this.manualForm.controls.barcode.value);}async lookup(raw:string){const barcode=normalizeBarcode(raw);if(!isSupportedBarcode(barcode)){this.error.set('Enter a valid EAN-8, EAN-13, UPC-A, or UPC-E barcode.');return;}this.loading.set(true);this.error.set(null);await this.scanner.stop();const r=await this.products.lookup(barcode);this.loading.set(false);if(r.status==='found'){this.product.set(r.product);const grams=r.userPreference?.defaultServingGrams??r.product.servingGrams;if(grams)this.form.patchValue({grams});else this.error.set('Serving size is unknown. Enter the grams consumed.');}else if(r.status==='not_found')this.error.set("We couldn’t find this product yet. Add it manually so it will be available next time.");else if(r.status==='temporarily_unavailable')this.error.set(navigator.onLine?'Product lookup is temporarily unavailable. Try again.':'You are offline and this product is not cached.');else this.error.set('This barcode is invalid.');}
 async add(){const p=this.product();if(!p||this.form.invalid)return;this.saving.set(true);const v=this.form.getRawValue();const r=await this.products.add(p,this.date(),this.mealType(),v.grams,v.servings);this.saving.set(false);if(r.error)this.error.set(r.error);else this.saved.emit();}scanAnother(){this.product.set(null);this.error.set(null);setTimeout(()=>void this.start());}quality(){const c=this.product()?.dataCompleteness;return c===null||c===undefined?'quality unknown':c>=.7?'good data coverage':'some details missing';}
}
