import { Component, EventEmitter, Input, OnInit, Output, computed, inject, signal } from '@angular/core';
import { MealType, MEAL_TYPE_LABELS, MEAL_TYPES } from '../../../core/models/meal-plan.model';
import { UserProfileService } from '../../../core/services/user-profile.service';
import { MealPlanAutogenerateResult } from '../../../core/models/meal-plan-autogenerate.model';
import { getAutogenerateDates } from '../../../shared/utils/meal-plan-autogenerate.utils';
import { formatDayLabel, toISODate } from '../../../shared/utils/meal-plan.utils';
import { MealPlanAutogenerateService } from '../services/meal-plan-autogenerate.service';

@Component({
  selector: 'app-meal-plan-autogenerate-dialog',
  standalone: true,
  template: `
    <div class="fixed inset-0 z-50 flex items-end justify-center bg-stone-950/40 p-0 sm:items-center sm:p-4" role="presentation" (click)="close()">
      <section data-tour="meal-plan-generator-dialog" class="max-h-[90vh] w-full overflow-y-auto rounded-t-2xl bg-white p-5 shadow-xl sm:max-w-lg sm:rounded-2xl sm:p-6"
        role="dialog" aria-modal="true" aria-labelledby="autogenerate-title" (click)="$event.stopPropagation()">
        <div class="flex items-start justify-between gap-4">
          <div><h2 id="autogenerate-title" class="text-xl font-semibold text-stone-900">Autogenerate meal plan</h2>
            <p class="mt-1 text-sm text-stone-600">Choose dates and meals. Existing meal slots will stay unchanged.</p></div>
          <button type="button" class="rounded-lg p-2 text-stone-500 hover:bg-stone-100" aria-label="Close autogenerate dialog" [disabled]="loading()" (click)="close()">✕</button>
        </div>

        <fieldset class="mt-6"><legend class="text-sm font-semibold text-stone-900">Dates</legend>
          <div class="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">
            @for (date of availableDates; track date) {
              <label class="flex cursor-pointer items-center gap-2 rounded-xl border border-stone-200 px-3 py-2 text-sm">
                <input type="checkbox" [checked]="selectedDates().has(date)" [disabled]="loading()" (change)="toggleDate(date)"> {{ dateLabel(date) }}
              </label>
            }
          </div>
        </fieldset>

        <fieldset class="mt-6"><legend class="text-sm font-semibold text-stone-900">Meals</legend>
          <div class="mt-3 grid grid-cols-2 gap-2">
            @for (mealType of mealTypes; track mealType) {
              <label class="flex cursor-pointer items-center gap-2 rounded-xl border border-stone-200 px-3 py-2 text-sm">
                <input type="checkbox" [checked]="selectedMeals().has(mealType)" [disabled]="loading()" (change)="toggleMeal(mealType)"> {{ mealLabel(mealType) }}
              </label>
            }
          </div>
        </fieldset>

        @if (feedback()) {
          <p class="mt-5 rounded-xl px-4 py-3 text-sm" [class.bg-red-50]="feedbackKind() === 'error'" [class.text-red-700]="feedbackKind() === 'error'"
            [class.bg-brand-50]="feedbackKind() !== 'error'" [class.text-brand-800]="feedbackKind() !== 'error'" role="status" aria-live="polite">{{ feedback() }}</p>
        }
        <div class="mt-6 flex justify-end gap-3">
          <button type="button" class="btn-secondary" [disabled]="loading()" (click)="close()">Cancel</button>
          <button type="button" class="btn-primary" [disabled]="!canGenerate()" (click)="generate()">{{ loading() ? 'Generating…' : 'Generate meals' }}</button>
        </div>
      </section>
    </div>
  `,
})
export class MealPlanAutogenerateDialogComponent implements OnInit {
  @Input({ required: true }) selectedDate = toISODate();
  @Output() readonly closed = new EventEmitter<void>();
  @Output() readonly generated = new EventEmitter<MealPlanAutogenerateResult>();
  private readonly autogenerate = inject(MealPlanAutogenerateService);
  private readonly profiles = inject(UserProfileService);
  readonly availableDates = getAutogenerateDates();
  readonly mealTypes = MEAL_TYPES;
  readonly selectedDates = signal(new Set<string>());
  readonly selectedMeals = signal(new Set<MealType>());
  readonly loading = signal(false);
  readonly feedback = signal<string | null>(null);
  readonly feedbackKind = signal<'success' | 'partial' | 'error'>('success');
  readonly canGenerate = computed(() => !this.loading() && this.selectedDates().size > 0 && this.selectedMeals().size > 0);

  ngOnInit(): void {
    this.selectedDates.set(new Set([this.availableDates.includes(this.selectedDate) ? this.selectedDate : this.availableDates[0]]));
    const enabled = this.profiles.profile()?.mealPlanningSettings.enabledMealSlots ?? ['breakfast', 'lunch', 'dinner'];
    const mapped = enabled.map((meal) => meal === 'snacks' ? 'snack' : meal).filter((meal): meal is MealType => MEAL_TYPES.includes(meal as MealType));
    this.selectedMeals.set(new Set(mapped.length ? mapped : ['breakfast', 'lunch', 'dinner']));
  }

  toggleDate(date: string): void { this.selectedDates.update((value) => this.toggleSet(value, date)); }
  toggleMeal(mealType: MealType): void { this.selectedMeals.update((value) => this.toggleSet(value, mealType)); }
  dateLabel(date: string): string { return formatDayLabel(date); }
  mealLabel(mealType: MealType): string { return MEAL_TYPE_LABELS[mealType]; }
  close(): void { if (!this.loading()) this.closed.emit(); }

  async generate(): Promise<void> {
    if (!this.canGenerate()) return;
    this.loading.set(true); this.feedback.set(null);
    try {
      const result = await this.autogenerate.generate({ dates: [...this.selectedDates()], mealTypes: [...this.selectedMeals()] });
      const partial = result.unfilledSlots.length > 0;
      this.feedbackKind.set(partial ? 'partial' : 'success');
      this.feedback.set(`${result.generatedCount} meal${result.generatedCount === 1 ? '' : 's'} generated. ${result.occupiedSlotsSkipped} occupied slot${result.occupiedSlotsSkipped === 1 ? '' : 's'} skipped.${partial ? ` ${result.unfilledSlots.length} slot${result.unfilledSlots.length === 1 ? '' : 's'} could not be filled.` : ''}`);
      this.generated.emit(result);
    } catch (error) {
      this.feedbackKind.set('error');
      this.feedback.set(error instanceof Error ? error.message : 'Could not autogenerate your meal plan.');
    } finally { this.loading.set(false); }
  }

  private toggleSet<T>(source: Set<T>, value: T): Set<T> {
    const next = new Set(source); next.has(value) ? next.delete(value) : next.add(value); return next;
  }
}
