import { FoodItem } from '../../core/models/food-item.model';
import { MealType } from '../../core/models/meal-plan.model';
import { MealSlotItem } from '../../core/models/meal-slot-item.model';
import { Recipe } from '../../core/models/recipe.model';
import { UserFoodProfile } from '../../core/models/user-profile.model';
import { buildSuggestion } from './suggestion-scoring.utils';
import { addDays, daysBetween, toISODate } from './meal-plan.utils';
import { normalizeNameKey } from './name-normalization.utils';

export interface AutogenerateSlot {
  date: string;
  mealType: MealType;
}

export interface RankedAutogenerateRecipe {
  recipe: Recipe;
  score: number;
  lastUsedDate: string | null;
}

export function getAutogenerateDates(today: string = toISODate()): string[] {
  const day = new Date(`${today}T00:00:00`).getDay();
  const daysUntilSunday = day === 0 ? 0 : 7 - day;
  return Array.from({ length: daysUntilSunday + 1 }, (_, index) => addDays(today, index));
}

export function validateAutogenerateSelection(
  dates: string[],
  mealTypes: MealType[],
  today: string = toISODate()
): string | null {
  if (dates.length === 0) return 'Select at least one date.';
  if (mealTypes.length === 0) return 'Select at least one meal.';
  const allowedDates = new Set(getAutogenerateDates(today));
  if (dates.some((date) => !allowedDates.has(date))) {
    return 'Dates must be between today and the upcoming Sunday.';
  }
  const validMeals = new Set<MealType>(['breakfast', 'lunch', 'dinner', 'snack']);
  if (mealTypes.some((mealType) => !validMeals.has(mealType))) return 'Invalid meal type.';
  return null;
}

function containsIngredient(recipe: Recipe, names: string[]): boolean {
  const ingredients = (recipe.ingredients ?? []).map((item) => normalizeNameKey(item.name));
  return names.some((name) => ingredients.some((ingredient) => ingredient.includes(name) || name.includes(ingredient)));
}

function profileAdjustment(recipe: Recipe, profile: UserFoodProfile | null): number | null {
  if (!profile) return 0;
  const allergens = profile.allergies.map((item) => item.normalizedName || normalizeNameKey(item.name));
  if (containsIngredient(recipe, allergens)) return null;

  const favorites = profile.favoriteIngredients.map((item) => item.normalizedName);
  const disliked = profile.dislikedIngredients.map((item) => item.normalizedName);
  let score = favorites.filter((name) => containsIngredient(recipe, [name])).length * 5;
  score -= disliked.filter((name) => containsIngredient(recipe, [name])).length * 8;

  const tags = new Set((recipe.tags ?? []).map((tag) => normalizeNameKey(tag)));
  for (const preference of profile.dietaryPreferences) {
    if (preference !== 'none' && tags.has(normalizeNameKey(preference))) score += 6;
  }
  return score;
}

export function rankRecipesForAutogeneration(
  recipes: Recipe[],
  mealType: MealType,
  inventory: FoodItem[],
  history: MealSlotItem[],
  profile: UserFoodProfile | null,
  today: string = toISODate()
): RankedAutogenerateRecipe[] {
  return recipes
    .filter((recipe) => recipe.meal_type === mealType)
    .map((recipe): RankedAutogenerateRecipe | null => {
      const adjustment = profileAdjustment(recipe, profile);
      if (adjustment === null) return null;
      const occurrences = history.filter((item) => item.recipe_id === recipe.id);
      const eatenCount = occurrences.filter((item) => item.status === 'eaten').length;
      const lastUsedDate = occurrences.reduce<string | null>(
        (latest, item) => (!latest || item.date > latest ? item.date : latest), null
      );
      const mostRecent = lastUsedDate ? daysBetween(lastUsedDate, today) : null;
      const recentPenalty = mostRecent === null || mostRecent < 0 ? 0
        : mostRecent <= 7 ? -20 : mostRecent <= 14 ? -10 : mostRecent <= 30 ? -5 : 0;
      const skippedPenalty = occurrences.some(
        (item) => item.status === 'skipped' && daysBetween(item.date, today) >= 0 && daysBetween(item.date, today) <= 30
      ) ? -15 : 0;
      const ratingAdjustment = recipe.rating === null ? 0 : (recipe.rating - 3) * 4;
      return {
        recipe,
        score: buildSuggestion(recipe, inventory, new Set()).score + adjustment +
          ratingAdjustment + Math.min(eatenCount * 3, 9) + recentPenalty + skippedPenalty,
        lastUsedDate,
      };
    })
    .filter((entry): entry is RankedAutogenerateRecipe => entry !== null)
    .sort((a, b) => b.score - a.score ||
      (a.lastUsedDate ?? '').localeCompare(b.lastUsedDate ?? '') ||
      a.recipe.title.localeCompare(b.recipe.title) || a.recipe.id.localeCompare(b.recipe.id));
}
