import { MealSlotItem } from '../../core/models/meal-slot-item.model';
import { Recipe } from '../../core/models/recipe.model';
import { UserFoodProfile } from '../../core/models/user-profile.model';
import { getAutogenerateDates, rankRecipesForAutogeneration, validateAutogenerateSelection } from './meal-plan-autogenerate.utils';

function recipe(id: string, overrides: Partial<Recipe> = {}): Recipe {
  return {
    id, user_id: null, title: id, description: null, prep_time_minutes: 30,
    cook_time_minutes: null, portions: 2, tags: [], rating: null, image_url: null,
    image_status: 'pending', is_base_recipe: true, base_recipe_id: null,
    meal_type: 'breakfast', category: null, difficulty: null, instructions: [],
    created_at: '2026-01-01T00:00:00Z', ingredients: [], ...overrides,
  };
}

function history(recipeId: string, date: string, status: MealSlotItem['status']): MealSlotItem {
  return { recipe_id: recipeId, date, status } as MealSlotItem;
}

describe('meal plan autogeneration utilities', () => {
  it('includes today and caps dates at Sunday', () => {
    expect(getAutogenerateDates('2026-07-17')).toEqual(['2026-07-17', '2026-07-18', '2026-07-19']);
    expect(getAutogenerateDates('2026-07-19')).toEqual(['2026-07-19']);
  });

  it('rejects empty, past, and post-Sunday selections', () => {
    expect(validateAutogenerateSelection([], ['breakfast'], '2026-07-17')).toContain('date');
    expect(validateAutogenerateSelection(['2026-07-16'], ['breakfast'], '2026-07-17')).toContain('Sunday');
    expect(validateAutogenerateSelection(['2026-07-20'], ['breakfast'], '2026-07-17')).toContain('Sunday');
  });

  it('matches meal types and excludes allergens', () => {
    const profile = { allergies: [{ normalizedName: 'peanut' }], favoriteIngredients: [], dislikedIngredients: [], dietaryPreferences: [] } as unknown as UserFoodProfile;
    const ranked = rankRecipesForAutogeneration([
      recipe('safe'), recipe('allergen', { ingredients: [{ id: 'i', recipe_id: 'allergen', name: 'Peanut', quantity: 1, unit: null }] }),
      recipe('lunch', { meal_type: 'lunch' }),
    ], 'breakfast', [], [], profile, '2026-07-17');
    expect(ranked.map((entry) => entry.recipe.id)).toEqual(['safe']);
  });

  it('applies ratings, completed boosts, recent and skipped penalties', () => {
    const recipes = [recipe('favorite', { rating: 5 }), recipe('recent'), recipe('skipped')];
    const ranked = rankRecipesForAutogeneration(recipes, 'breakfast', [], [
      history('favorite', '2026-05-01', 'eaten'), history('favorite', '2026-05-08', 'eaten'),
      history('recent', '2026-07-15', 'planned'), history('skipped', '2026-06-30', 'skipped'),
    ], null, '2026-07-17');
    expect(ranked[0].recipe.id).toBe('favorite');
    expect(ranked.find((entry) => entry.recipe.id === 'recent')!.score).toBeLessThan(ranked[0].score);
    expect(ranked.find((entry) => entry.recipe.id === 'skipped')!.score).toBeLessThan(ranked[0].score);
  });

  it('orders score ties by least recent use, title, then id', () => {
    const ranked = rankRecipesForAutogeneration([
      recipe('b', { title: 'Same' }), recipe('a', { title: 'Same' }), recipe('unused', { title: 'Alpha' }),
    ], 'breakfast', [], [history('a', '2026-06-01', 'planned'), history('b', '2026-06-10', 'planned')], null, '2026-07-17');
    expect(ranked.map((entry) => entry.recipe.id)).toEqual(['unused', 'a', 'b']);
  });
});
