import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import {
  MEAL_TYPES,
  MEAL_TYPE_LABELS,
  MEAL_TYPE_TIME_RANGES,
  MealType,
} from '../../core/models/meal-plan.model';
import { MealSlotItem } from '../../core/models/meal-slot-item.model';
import { MealPlanService } from '../../core/services/meal-plan.service';
import { RecipeService } from '../../core/services/recipe.service';
import { EntitlementService } from '../../core/services/entitlement.service';
import { ConfirmDialogService } from '../../core/services/confirm-dialog.service';
import { getMondayOfWeek } from '../../shared/utils/meal-plan.utils';
import { MealStreakService } from '../../core/services/meal-streak.service';
import { LoadingStateComponent } from '../../shared/components/loading-state/loading-state.component';
import {
  formatDayShort,
  formatFullDayHeading,
  formatWeekRangeCompact,
  isPastDate,
  isToday,
  toISODate,
} from '../../shared/utils/meal-plan.utils';
import { MealSlotItemStatus } from '../../core/models/meal-slot-item.model';
import { ConfettiCelebrationComponent } from './components/confetti-celebration/confetti-celebration.component';
import { UpgradePromptComponent } from '../../shared/components/upgrade-prompt/upgrade-prompt.component';
import { TodayProgressSwitcherComponent } from '../../shared/components/today-progress-switcher/today-progress-switcher.component';
import { NutritionProgressService } from '../../core/services/nutrition-progress.service';
import { NutritionTargetsService } from '../../core/services/nutrition-targets.service';
import { MealStatusControlComponent } from './components/meal-status-control/meal-status-control.component';
import { MealPlanProgressService } from './services/meal-plan-progress.service';
import { ToCookService } from './services/to-cook.service';
import { MealPlanAutogenerateDialogComponent } from './components/meal-plan-autogenerate-dialog.component';
import { MealSlotItemsComponent } from './meal-slot-items.component';
import { MealSlotItemPickerComponent } from './meal-slot-item-picker.component';
import { AddFoodActionMenuComponent, FoodActionChoice } from './components/add-food-action-menu/add-food-action-menu.component';
import { ManualFoodLogDialogComponent } from './components/manual-food-log-dialog/manual-food-log-dialog.component';
import { VoiceFoodLogDialogComponent } from './components/voice-food-log-dialog/voice-food-log-dialog.component';
import { PhotoFoodLogDialogComponent } from './components/photo-food-log-dialog/photo-food-log-dialog.component';
import { BarcodeProductDialogComponent } from './components/barcode-product-dialog.component';
import {
  PhotoCaptureContext,
  PhotoCaptureSelection,
  RecipePhotoDraft,
} from '../../core/models/photo-food-capture.model';
import { PhotoCaptureFlowComponent } from '../photo-food-capture/photo-capture-flow.component';
import { PhotoMealPlanFormComponent } from '../photo-food-capture/photo-meal-plan-form.component';
import { MealPhotoDraftFormComponent } from '../photo-food-capture/meal-photo-draft-form.component';
import { MealPhotoAnalysisCompleteEvent } from '../../core/models/meal-photo-analysis.model';
import { RecipeFormDialogComponent } from '../recipes/recipe-form/recipe-form-dialog.component';
import { getMealSlotItemDisplayName } from '../../shared/utils/prepared-portion.utils';
import { getDefaultMealTypeForNow } from '../../shared/utils/food-log.utils';
import { DayMealProgress } from './models/day-meal-progress.model';
import {
  getDayProgressTitle,
} from './utils/meal-slot-completion.utils';
import {
  countReadySlotsForDay,
  getSlotDisplayStatus,
} from './utils/meal-slot-status.utils';
import { FirstTourEventsService } from '../../core/onboarding/first-tour-events.service';
import { MealPlanAutogenerateResult } from '../../core/models/meal-plan-autogenerate.model';

interface SelectedSlot {
  date: string;
  mealType: MealType;
  replaceItemId?: string;
}

@Component({
  selector: 'app-meal-plan',
  standalone: true,
  imports: [
    LoadingStateComponent,
    MealSlotItemsComponent,
    MealSlotItemPickerComponent,
    AddFoodActionMenuComponent,
    ManualFoodLogDialogComponent,
    VoiceFoodLogDialogComponent,
    PhotoFoodLogDialogComponent,
    BarcodeProductDialogComponent,
    PhotoCaptureFlowComponent,
    PhotoMealPlanFormComponent,
    MealPhotoDraftFormComponent,
    RecipeFormDialogComponent,
    TodayProgressSwitcherComponent,
    MealStatusControlComponent,
    ConfettiCelebrationComponent,
    UpgradePromptComponent,
    MealPlanAutogenerateDialogComponent,
  ],
  template: `
    <app-confetti-celebration [active]="showConfetti()" />

    <div class="page">
      @if (mealPlanLimitMessage()) {
        <app-upgrade-prompt
          title="Meal plan limit reached"
          [message]="mealPlanLimitMessage()!"
        />
      }
      <!-- <div>
        <h1 class="page-title">Meal Plan</h1>
        <p class="page-subtitle">Plan your week and reduce waste.</p>
      </div>-->

      <!-- Week navigation -->
      <div class="flex items-center justify-between gap-3">
        <button
          type="button"
          class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-stone-200 bg-white text-stone-600 transition-colors hover:bg-stone-50"
          aria-label="Previous week"
          (click)="onPreviousWeek()"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-5 w-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
          </svg>
        </button>

        <div class="min-w-0 text-center">
          <p class="text-base font-semibold text-stone-900">{{ weekRangeLabel() }}</p>
          @if (!isCurrentWeek()) {
            <button
              type="button"
              class="mt-0.5 text-xs font-medium text-brand-700 hover:text-brand-800"
              (click)="onTodayWeek()"
            >
              Jump to this week
            </button>
          }
        </div>

        <button
          type="button"
          class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-stone-200 bg-white text-stone-600 transition-colors hover:bg-stone-50"
          aria-label="Next week"
          (click)="onNextWeek()"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-5 w-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
          </svg>
        </button>
      </div>

      <!-- Week day picker -->
      <div class="meal-week-strip grid w-full grid-cols-7 gap-0.5 sm:gap-1">
        @for (date of mealPlanService.weekDates(); track date) {
          @let day = formatDayShort(date);
          @let mealCount = mealsForDate(date);
          <button
            type="button"
            class="meal-week-day flex w-full min-h-11 flex-col items-center justify-center rounded-lg px-0 py-1.5 transition-colors sm:min-h-0 sm:rounded-xl sm:px-1 sm:py-2.5"
            [class.bg-brand-600]="selectedDate() === date"
            [class.text-white]="selectedDate() === date"
            [class.bg-stone-100]="selectedDate() !== date"
            [class.text-stone-700]="selectedDate() !== date"
            [class.ring-2]="isTodayDate(date) && selectedDate() !== date"
            [class.ring-brand-600]="isTodayDate(date) && selectedDate() !== date"
            [class.ring-offset-1]="isTodayDate(date) && selectedDate() !== date"
            [class.opacity-60]="isPastDate(date)"
            [attr.aria-pressed]="selectedDate() === date"
            [attr.aria-current]="isTodayDate(date) ? 'date' : null"
            (click)="selectDate(date)"
          >
            <span class="text-[9px] font-medium leading-none tracking-wide sm:text-xs">{{ day.weekday }}</span>
            <span class="mt-0.5 text-sm font-semibold leading-none sm:text-lg">{{ day.day }}</span>
            <span class="mt-1 flex h-1.5 items-center justify-center gap-0.5" aria-hidden="true">
              @for (dot of mealCountDots(mealCount); track $index) {
                <span
                  class="h-1 w-1 rounded-full"
                  [class.bg-white/80]="selectedDate() === date"
                  [class.bg-brand-600]="selectedDate() !== date"
                ></span>
              }
            </span>
          </button>
        }
      </div>

      @if (selectedSlot()) {
        <app-meal-slot-item-picker
          [date]="selectedSlot()!.date"
          [mealType]="selectedSlot()!.mealType"
          [replaceItemId]="selectedSlot()!.replaceItemId ?? null"
          (added)="onItemAdded()"
          (photoRequested)="onPhotoRequestedFromPicker()"
          (cancelled)="selectedSlot.set(null)"
        />
      }

      @if (showAddFoodMenu()) {
        <app-add-food-action-menu
          (selected)="onFoodActionSelected($event)"
          (cancelled)="showAddFoodMenu.set(false)"
        />
      }

      @if (showManualFoodLog()) {
        <app-manual-food-log-dialog
          (saved)="onFoodLogSaved()"
          (cancelled)="showManualFoodLog.set(false)"
        />
      }

      @if (showVoiceFoodLog()) {
        <app-voice-food-log-dialog
          (saved)="onFoodLogSaved()"
          (cancelled)="showVoiceFoodLog.set(false)"
          (switchToManual)="openManualFromVoice()"
        />
      }

      @if (showPhotoCapture()) {
        <app-photo-capture-flow
          [context]="photoCaptureContext()"
          [aiMealPlanMode]="photoAiMealPlanMode()"
          (destinationChosen)="onPhotoCaptureChosen($event)"
          (draftReady)="onPhotoDraftReady($event)"
          (manualFallback)="onPhotoManualFallback($event)"
          (cancelled)="closePhotoCapture()"
        />
      }

      @if (showPhotoDraftForm() && photoDraftEvent()) {
        <app-meal-photo-draft-form
          [draft]="photoDraftEvent()!.draft"
          [file]="photoDraftEvent()!.file"
          [previewUrl]="photoDraftEvent()!.previewUrl"
          [analysisId]="photoDraftEvent()!.analysisId"
          [context]="photoCaptureContext()"
          (saved)="onPhotoDraftSaved()"
          (cancelled)="closePhotoDraftForm()"
        />
      }

      @if (showPhotoRecipeForm() && photoDraft()) {
        <app-recipe-form-dialog
          [photoDraft]="photoDraft()"
          (saved)="onPhotoRecipeCreated()"
          (cancelled)="closePhotoRecipeForm()"
        />
      }
      @if (showPhotoMealPlan() && photoSelection()) {
        <app-photo-meal-plan-form
          [file]="photoSelection()!.file"
          [previewUrl]="photoSelection()!.previewUrl"
          [context]="photoCaptureContext()"
          [suggestedName]="photoSelection()!.analysis?.suggestedName ?? null"
          (saved)="onPhotoFlowSaved()"
          (cancelled)="closePhotoFlows()"
        />
      }

      @if (showPhotoFoodLog() && photoSelection()) {
        <app-photo-food-log-dialog
          [initialFile]="photoSelection()!.file"
          [initialPreviewUrl]="photoSelection()!.previewUrl"
          [context]="photoCaptureContext()"
          [suggestedName]="photoSelection()!.analysis?.suggestedName ?? null"
          (saved)="onPhotoFlowSaved()"
          (cancelled)="closePhotoFlows()"
        />
      }
      @if (showBarcodeProduct()) {
        <app-barcode-product-dialog [date]="selectedDate()" [mealType]="barcodeMealType()" (saved)="onBarcodeSaved()" (cancelled)="showBarcodeProduct.set(false)" />
      }
      @if (showAutogenerateDialog()) {
        <app-meal-plan-autogenerate-dialog
          [selectedDate]="selectedDate()"
          (closed)="showAutogenerateDialog.set(false)"
          (generated)="onMealsAutogenerated($event)"
        />
      }

      @if (mealPlanService.loading()) {
        <app-loading-state message="Loading meal plan..." />
      } @else if (mealPlanService.error()) {
        <p class="alert-error">
          {{ mealPlanService.error() }}
        </p>
      } @else {
        <!-- Selected day meals -->
        <div>
          <div class="mb-4 flex flex-wrap items-center justify-between gap-2">
            <h2 class="text-lg font-semibold text-stone-900">{{ selectedDayHeading() }}</h2>
            <div class="flex flex-wrap items-center gap-2">
              @if (isTodayDate(selectedDate())) {
                <span class="rounded-full bg-brand-50 px-2.5 py-0.5 text-xs font-semibold text-brand-700">Today</span>
              }
              <!-- Hidden for now — re-enable when add-food flow is ready for users
              <button type="button" class="btn-primary-sm" (click)="showAddFoodMenu.set(true)">
                Add food
              </button>
              -->
            </div>
          </div>

          <app-today-progress-switcher
            class="mb-5 block"
            [title]="dayProgressTitle()"
            [selectedDate]="selectedDate()"
            [mealProgress]="dayProgress()"
            [nutritionProgress]="dayNutritionProgress()"
            [isNutritionProfileComplete]="nutritionTargetsService.hasRequiredProfileData()"
            [readyCount]="dayReadyCount()"
            (completeProfileClicked)="goToNutritionProfile()"
          />

          <div class="mb-5 flex justify-center">
            <button
              type="button"
              class="btn-primary-sm"
              data-tour="meal-plan-generator"
              (click)="showAutogenerateDialog.set(true)"
            >
              Generate meal plan
            </button>
          </div>

          @if (streakFeedbackMessage()) {
            <p
              class="mb-5 rounded-lg bg-brand-50 px-4 py-3 text-sm font-medium text-brand-800"
              role="status"
              aria-live="polite"
            >
              {{ streakFeedbackMessage() }}
            </p>
          }

          <div class="space-y-6">
            @for (mealType of mealTypes; track mealType) {
              <section>
                <div class="mb-3 flex items-center justify-between gap-3">
                  <div class="min-w-0">
                    <h3 class="text-base font-semibold text-stone-900">{{ mealTypeLabel(mealType) }}</h3>
                    <p class="text-sm text-stone-600">{{ mealTypeTimeRange(mealType) }}</p>
                  </div>
                  @if (itemsFor(selectedDate(), mealType).length > 0) {
                    <app-meal-status-control
                      [mealType]="mealType"
                      [displayStatus]="slotDisplayStatus(selectedDate(), mealType)"
                      [loading]="isSlotCompleting(selectedDate(), mealType)"
                      [tourTarget]="tourTargetMealType() === mealType"
                      (statusChange)="onSlotStatusChange(selectedDate(), mealType, $event)"
                    />
                  }
                </div>

                @if (itemsFor(selectedDate(), mealType).length > 0) {
                  <app-meal-slot-items
                    [items]="itemsFor(selectedDate(), mealType)"
                    [removingId]="removingId()"
                    [canAdd]="canAddToSelectedDate()"
                    [canChange]="canAddToSelectedDate()"
                    [status]="slotDisplayStatus(selectedDate(), mealType)"
                    (addItem)="openPicker(selectedDate(), mealType)"
                    (removeItem)="onRemoveItem($event)"
                    (changeItem)="onChangeItem($event)"
                  />
                } @else if (isPastDate(selectedDate())) {
                  <div
                    class="flex w-full items-center gap-3 rounded-xl border border-dashed border-stone-200 bg-stone-50/40 p-4 text-left"
                  >
                    <div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-white ring-1 ring-stone-200">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6 text-stone-300">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                      </svg>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-stone-500">No items planned</p>
                      <p class="text-sm text-stone-400">Past meals can't be changed</p>
                    </div>
                  </div>
                } @else {
                  <button
                    type="button"
                    class="flex w-full items-center gap-3 rounded-xl border border-dashed border-stone-300 bg-stone-50/60 p-4 text-left transition-colors hover:border-brand-300 hover:bg-brand-50/30"
                    (click)="openPicker(selectedDate(), mealType)"
                  >
                    <div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-white ring-1 ring-stone-200">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-6 w-6 text-stone-400">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                      </svg>
                    </div>
                    <div>
                      <p class="text-sm font-medium text-stone-600">No items planned</p>
                      <p class="text-sm font-semibold text-brand-700">Tap to add item</p>
                    </div>
                  </button>
                }
              </section>
            }
          </div>
        </div>

        <div class="flex justify-center pt-2">
          <button
            type="button"
            class="text-sm font-medium text-stone-500 transition-colors hover:text-brand-700 disabled:opacity-50"
            [disabled]="duplicating()"
            (click)="onDuplicatePreviousWeek()"
          >
            {{ duplicating() ? 'Copying last week...' : 'Duplicate previous week' }}
          </button>
        </div>
      }
    </div>
  `,
})
export class MealPlanComponent implements OnInit {
  readonly mealPlanService = inject(MealPlanService);
  private readonly recipeService = inject(RecipeService);
  private readonly entitlementService = inject(EntitlementService);
  private readonly confirmDialog = inject(ConfirmDialogService);
  private readonly progressService = inject(MealPlanProgressService);
  private readonly toCookService = inject(ToCookService);
  private readonly nutritionProgressService = inject(NutritionProgressService);
  readonly nutritionTargetsService = inject(NutritionTargetsService);
  private readonly mealStreakService = inject(MealStreakService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  private readonly firstTourEvents = inject(FirstTourEventsService);

  readonly mealTypes = MEAL_TYPES;
  readonly selectedSlot = signal<SelectedSlot | null>(null);
  readonly showAddFoodMenu = signal(false);
  readonly showAutogenerateDialog = signal(false);
  readonly showManualFoodLog = signal(false);
  readonly showVoiceFoodLog = signal(false);
  readonly showPhotoCapture = signal(false);
  readonly showPhotoMealPlan = signal(false);
  readonly showPhotoFoodLog = signal(false);
  readonly showPhotoDraftForm = signal(false);
  readonly photoAiMealPlanMode = signal(false);
  readonly photoDraftEvent = signal<MealPhotoAnalysisCompleteEvent | null>(null);
  readonly photoSlotContext = signal<PhotoCaptureContext | null>(null);
  readonly showBarcodeProduct = signal(false);
  readonly barcodeMealType = signal<MealType>('snack');
  readonly showPhotoRecipeForm = signal(false);
  readonly photoSelection = signal<PhotoCaptureSelection | null>(null);
  readonly photoDraft = signal<RecipePhotoDraft | null>(null);
  readonly photoCaptureContext = computed<PhotoCaptureContext>(() => {
    const slotContext = this.photoSlotContext();
    if (slotContext) {
      return slotContext;
    }
    return {
      defaultDate: this.selectedDate(),
      defaultMealType: getDefaultMealTypeForNow(),
    };
  });
  readonly selectedDate = signal(toISODate(new Date()));
  readonly tourTargetMealType = signal<MealType | null>(null);
  readonly removingId = signal<string | null>(null);
  readonly duplicating = signal(false);
  readonly mealPlanLimitMessage = signal<string | null>(null);
  readonly completingSlotKey = signal<string | null>(null);
  readonly showConfetti = signal(false);
  private readonly celebrationArmed = signal(false);

  readonly weekRangeLabel = computed(() =>
    formatWeekRangeCompact(this.mealPlanService.weekDates())
  );

  readonly selectedDayHeading = computed(() => formatFullDayHeading(this.selectedDate()));

  readonly dayProgress = computed(() =>
    this.progressService.calculateDayProgress(
      this.selectedDate(),
      this.mealPlanService.entries()
    )
  );

  readonly dayNutritionProgress = computed(() =>
    this.nutritionProgressService.calculateDayNutritionProgress(
      this.selectedDate(),
      this.mealPlanService.entries()
    )
  );

  readonly dayReadyCount = computed(() =>
    countReadySlotsForDay(this.selectedDate(), this.mealPlanService.entries())
  );

  readonly dayProgressTitle = computed(() =>
    getDayProgressTitle(this.selectedDate(), this.isTodayDate(this.selectedDate()))
  );

  readonly streakFeedbackMessage = computed(() => {
    if (!this.isTodayDate(this.selectedDate())) {
      return null;
    }
    return this.mealStreakService.lastFeedbackMessage();
  });

  ngOnInit(): void {
    const requestedDate = this.route.snapshot.queryParamMap.get('date');
    const requestedMealType = this.route.snapshot.queryParamMap.get('tourMealType') as MealType | null;
    if (requestedMealType && MEAL_TYPES.includes(requestedMealType)) {
      this.tourTargetMealType.set(requestedMealType);
    }
    void Promise.all([
      this.mealPlanService.loadWeekAndToday(requestedDate ? getMondayOfWeek(requestedDate) : undefined).then(() => {
        if (requestedDate && this.mealPlanService.weekDates().includes(requestedDate)) {
          this.selectedDate.set(requestedDate);
        } else {
          this.syncSelectedDateToWeek();
        }
        this.armCelebrationTracking();
      }),
      this.nutritionTargetsService.ensureProfileLoaded(),
      this.recipeService.loadBaseRecipes(),
    ]);
  }

  goToNutritionProfile(): void {
    void this.router.navigate(['/profile'], { queryParams: { section: 'nutrition' } });
  }

  slotDisplayStatus(date: string, mealType: MealType) {
    return getSlotDisplayStatus(this.itemsFor(date, mealType));
  }

  isSlotCompleting(date: string, mealType: MealType): boolean {
    return this.completingSlotKey() === this.slotKey(date, mealType);
  }

  async onSlotStatusChange(
    date: string,
    mealType: MealType,
    status: MealSlotItemStatus
  ): Promise<void> {
    const previous = this.dayProgress();
    const key = this.slotKey(date, mealType);
    this.completingSlotKey.set(key);

    const { error } = await this.progressService.setMealSlotStatus(date, mealType, status);
    this.completingSlotKey.set(null);

    if (error) {
      return;
    }

    const persistedIds = this.itemsFor(date, mealType).map((item) => item.id);
    this.firstTourEvents.publish({
      type: 'meal-status-persisted',
      itemIds: persistedIds,
      status,
    });
    await this.afterSlotStatusUpdated(previous);
  }

  private async afterSlotStatusUpdated(previous: DayMealProgress): Promise<void> {
    await Promise.all([
      this.mealPlanService.getTodayMeals(),
      this.toCookService.refresh(),
    ]);

    const current = this.dayProgress();
    if (
      this.celebrationArmed() &&
      this.progressService.shouldTriggerDayCompletedCelebration(previous, current)
    ) {
      this.triggerConfetti();
    }
  }

  itemsFor(date: string, mealType: MealType): MealSlotItem[] {
    return this.mealPlanService.getItemsForSlot(date, mealType);
  }

  mealsForDate(date: string): number {
    return this.mealTypes.filter((mealType) => this.itemsFor(date, mealType).length > 0).length;
  }

  formatDayShort = formatDayShort;

  mealTypeLabel(mealType: MealType): string {
    return MEAL_TYPE_LABELS[mealType];
  }

  mealTypeTimeRange(mealType: MealType): string {
    return MEAL_TYPE_TIME_RANGES[mealType];
  }

  isTodayDate(date: string): boolean {
    return isToday(date);
  }

  isPastDate = isPastDate;

  canAddToSelectedDate(): boolean {
    return !isPastDate(this.selectedDate());
  }

  isCurrentWeek(): boolean {
    const today = toISODate(new Date());
    return this.mealPlanService.weekDates().includes(today);
  }

  mealCountDots(count: number): number[] {
    return Array.from({ length: Math.min(count, 3) }, (_, index) => index);
  }

  openPicker(date: string, mealType: MealType): void {
    if (isPastDate(date)) {
      return;
    }
    if (!this.canModifyMealPlanDate(date)) {
      return;
    }
    this.selectedSlot.set({ date, mealType });
  }

  onChangeItem(item: MealSlotItem): void {
    if (isPastDate(item.date)) {
      return;
    }
    if (!this.canModifyMealPlanDate(item.date)) {
      return;
    }
    this.selectedSlot.set({
      date: item.date,
      mealType: item.meal_type,
      replaceItemId: item.id,
    });
  }

  private canModifyMealPlanDate(date: string): boolean {
    const weekStart = getMondayOfWeek(date);
    if (this.entitlementService.canCreateOrActivateMealPlanWeek(weekStart)) {
      this.mealPlanLimitMessage.set(null);
      return true;
    }
    this.mealPlanLimitMessage.set(
      'Free accounts can plan meals for the current week only. Upgrade to plan additional weeks.'
    );
    return false;
  }

  onFoodActionSelected(choice: FoodActionChoice): void {
    this.showAddFoodMenu.set(false);
    switch (choice) {
      case 'manual':
        this.showManualFoodLog.set(true);
        break;
      case 'voice':
        this.showVoiceFoodLog.set(true);
        break;
      case 'photo':
        this.photoSlotContext.set(null);
        this.photoAiMealPlanMode.set(false);
        this.showPhotoCapture.set(true);
        break;
      case 'barcode':
        this.barcodeMealType.set(this.selectedSlot()?.mealType ?? 'snack');
        this.showBarcodeProduct.set(true);
        break;
    }
  }

  onPhotoRequestedFromPicker(): void {
    const slot = this.selectedSlot();
    if (!slot) {
      return;
    }
    this.photoSlotContext.set({
      defaultDate: slot.date,
      defaultMealType: slot.mealType,
    });
    this.selectedSlot.set(null);
    this.photoAiMealPlanMode.set(true);
    this.showPhotoCapture.set(true);
  }

  onPhotoCaptureChosen(selection: PhotoCaptureSelection): void {
    this.closePhotoCapture();
    this.photoSelection.set(selection);

    switch (selection.destination) {
      case 'recipe':
        this.photoDraft.set({
          file: selection.file,
          previewUrl: selection.previewUrl,
          analysis: selection.analysis,
        });
        this.showPhotoRecipeForm.set(true);
        break;
      case 'mealPlan':
        this.showPhotoMealPlan.set(true);
        break;
      case 'foodLog':
        this.showPhotoFoodLog.set(true);
        break;
    }
  }

  onPhotoDraftReady(event: MealPhotoAnalysisCompleteEvent): void {
    this.closePhotoCapture();
    this.photoDraftEvent.set(event);
    this.showPhotoDraftForm.set(true);
  }

  onPhotoManualFallback(selection: PhotoCaptureSelection): void {
    this.closePhotoCapture();
    this.photoSelection.set(selection);
    this.showPhotoMealPlan.set(true);
  }

  async onPhotoDraftSaved(): Promise<void> {
    this.closePhotoDraftForm();
    await this.onFoodLogSaved();
  }

  closePhotoCapture(): void {
    this.showPhotoCapture.set(false);
    this.photoAiMealPlanMode.set(false);
  }

  closePhotoDraftForm(): void {
    this.showPhotoDraftForm.set(false);
    this.photoDraftEvent.set(null);
    this.photoSlotContext.set(null);
  }

  onPhotoRecipeCreated(): void {
    this.closePhotoRecipeForm();
  }

  closePhotoRecipeForm(): void {
    this.showPhotoRecipeForm.set(false);
    this.photoDraft.set(null);
    this.photoSelection.set(null);
  }

  async onPhotoFlowSaved(): Promise<void> {
    this.closePhotoFlows();
    await this.onFoodLogSaved();
  }

  closePhotoFlows(): void {
    this.showPhotoMealPlan.set(false);
    this.showPhotoFoodLog.set(false);
    this.photoSelection.set(null);
    this.photoSlotContext.set(null);
  }

  openManualFromVoice(): void {
    this.showVoiceFoodLog.set(false);
    this.showManualFoodLog.set(true);
  }

  async onFoodLogSaved(): Promise<void> {
    this.showManualFoodLog.set(false);
    this.showVoiceFoodLog.set(false);
    this.closePhotoFlows();
    this.closePhotoDraftForm();
    await this.mealPlanService.loadWeekAndToday(this.mealPlanService.weekStart());
    await this.toCookService.refresh();
  }
  async onBarcodeSaved():Promise<void>{this.showBarcodeProduct.set(false);await this.mealPlanService.loadWeekAndToday(this.mealPlanService.weekStart());}

  async onItemAdded(): Promise<void> {
    this.selectedSlot.set(null);
    await Promise.all([
      this.mealPlanService.getTodayMeals(),
      this.toCookService.refresh(),
    ]);
  }

  async onMealsAutogenerated(result: MealPlanAutogenerateResult): Promise<void> {
    this.showAutogenerateDialog.set(false);
    await this.toCookService.refresh();
    this.firstTourEvents.publish({ type: 'meal-plan-generated', result });
  }

  async onRemoveItem(item: MealSlotItem): Promise<void> {
    const title = getMealSlotItemDisplayName(item);
    const confirmed = await this.confirmDialog.confirm({
      title: 'Remove from meal',
      message: `Remove "${title}" from this meal slot?`,
      confirmLabel: 'Remove',
      danger: true,
    });
    if (!confirmed) {
      return;
    }

    this.removingId.set(item.id);
    await this.mealPlanService.removeSlotItem(item.id);
    this.removingId.set(null);
    await Promise.all([
      this.mealPlanService.getTodayMeals(),
      this.toCookService.refresh(),
    ]);
  }

  selectDate(date: string): void {
    this.selectedDate.set(date);
    this.selectedSlot.set(null);
  }

  async onPreviousWeek(): Promise<void> {
    this.mealPlanService.goToPreviousWeek();
    this.selectedSlot.set(null);
    await this.mealPlanService.getMealPlanForWeek(this.mealPlanService.weekStart());
    this.syncSelectedDateToWeek();
  }

  async onNextWeek(): Promise<void> {
    this.mealPlanService.goToNextWeek();
    this.selectedSlot.set(null);
    await this.mealPlanService.getMealPlanForWeek(this.mealPlanService.weekStart());
    this.syncSelectedDateToWeek();
  }

  async onTodayWeek(): Promise<void> {
    this.mealPlanService.goToTodayWeek();
    this.selectedSlot.set(null);
    await this.mealPlanService.loadWeekAndToday();
    this.selectedDate.set(toISODate(new Date()));
  }

  async onDuplicatePreviousWeek(): Promise<void> {
    if (!this.entitlementService.canCreateOrActivateMealPlanWeek(this.mealPlanService.weekStart())) {
      this.mealPlanLimitMessage.set(
        'Free accounts can plan meals for the current week only. Upgrade to duplicate weeks.'
      );
      return;
    }

    const confirmed = await this.confirmDialog.confirm({
      title: 'Duplicate previous week',
      message:
        "Copy last week's meals into empty slots for this week? Existing meals will not be overwritten.",
      confirmLabel: 'Copy meals',
    });
    if (!confirmed) {
      return;
    }

    this.duplicating.set(true);
    const { copiedCount, error } = await this.mealPlanService.duplicatePreviousWeek(
      this.mealPlanService.weekStart()
    );
    this.duplicating.set(false);

    if (!error && copiedCount === 0) {
      await this.confirmDialog.alert({
        title: 'Nothing to copy',
        message: 'No empty slots were available to copy into.',
      });
    }
  }

  private syncSelectedDateToWeek(): void {
    const weekDates = this.mealPlanService.weekDates();
    const current = this.selectedDate();

    if (weekDates.includes(current)) {
      return;
    }

    const today = toISODate(new Date());
    if (weekDates.includes(today)) {
      this.selectedDate.set(today);
      return;
    }

    const firstUpcoming = weekDates.find((date) => !isPastDate(date));
    this.selectedDate.set(firstUpcoming ?? weekDates[0]);
  }

  private slotKey(date: string, mealType: MealType): string {
    return `${date}|${mealType}`;
  }

  private armCelebrationTracking(): void {
    this.celebrationArmed.set(true);
  }

  private triggerConfetti(): void {
    this.showConfetti.set(false);
    requestAnimationFrame(() => this.showConfetti.set(true));
    window.setTimeout(() => this.showConfetti.set(false), 1100);
  }
}
