import { defineBaseRecipes } from './helpers';

export const breakfastBaseRecipes = defineBaseRecipes('0001', [
  {
    title: 'Classic Oatmeal Bowl',
    description: 'Warm oats with milk, topped with fruit and a drizzle of honey.',
    meal_type: 'breakfast',
    category: 'Oats',
    ingredients: [
      { name: 'rolled oats', quantity: 0.5, unit: 'cup' },
      { name: 'milk', quantity: 1, unit: 'cup' },
      { name: 'banana', quantity: 0.5, unit: null },
      { name: 'honey', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Combine oats and milk in a small pot.',
      'Simmer 5 minutes, stirring, until creamy.',
      'Top with sliced banana and honey.',
    ],
    tags: ['quick', 'budget friendly', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 5,
  },
  {
    title: 'Overnight Oats',
    description: 'No-cook oats soaked overnight for a ready-to-eat breakfast.',
    meal_type: 'breakfast',
    category: 'Oats',
    ingredients: [
      { name: 'rolled oats', quantity: 0.5, unit: 'cup' },
      { name: 'milk', quantity: 0.5, unit: 'cup' },
      { name: 'yogurt', quantity: 0.25, unit: 'cup' },
      { name: 'berries', quantity: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Mix oats, milk, and yogurt in a jar.',
      'Refrigerate overnight.',
      'Stir and top with berries before eating.',
    ],
    tags: ['no cook', 'meal prep friendly', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Banana Peanut Butter Oats',
    description: 'Creamy oats with banana and peanut butter for staying power.',
    meal_type: 'breakfast',
    category: 'Oats',
    ingredients: [
      { name: 'rolled oats', quantity: 0.5, unit: 'cup' },
      { name: 'milk', quantity: 1, unit: 'cup' },
      { name: 'banana', quantity: 1, unit: null },
      { name: 'peanut butter', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook oats with milk until soft.',
      'Stir in peanut butter.',
      'Top with sliced banana.',
    ],
    tags: ['high protein', 'budget friendly', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 5,
  },
  {
    title: 'Apple Cinnamon Oats',
    description: 'Comforting oats with diced apple and cinnamon.',
    meal_type: 'breakfast',
    category: 'Oats',
    ingredients: [
      { name: 'rolled oats', quantity: 0.5, unit: 'cup' },
      { name: 'milk', quantity: 1, unit: 'cup' },
      { name: 'apple', quantity: 1, unit: null },
      { name: 'cinnamon', quantity: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Dice apple and add to pot with oats and milk.',
      'Simmer until apples soften and oats are creamy.',
      'Stir in cinnamon and serve warm.',
    ],
    tags: ['quick', 'budget friendly', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 8,
  },
  {
    title: 'Greek Yogurt Bowl',
    description: 'Thick yogurt with granola, nuts, and fresh fruit.',
    meal_type: 'breakfast',
    category: 'Yogurt Bowl',
    ingredients: [
      { name: 'greek yogurt', quantity: 1, unit: 'cup' },
      { name: 'granola', quantity: 0.25, unit: 'cup' },
      { name: 'mixed nuts', quantity: 2, unit: 'tbsp' },
      { name: 'berries', quantity: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Spoon yogurt into a bowl.',
      'Top with granola, nuts, and berries.',
    ],
    tags: ['no cook', 'high protein', 'quick'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Yogurt with Banana and Honey',
    description: 'Simple yogurt bowl sweetened with banana and honey.',
    meal_type: 'breakfast',
    category: 'Yogurt Bowl',
    ingredients: [
      { name: 'yogurt', quantity: 1, unit: 'cup' },
      { name: 'banana', quantity: 1, unit: null },
      { name: 'honey', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Slice banana over yogurt.',
      'Drizzle with honey and serve.',
    ],
    tags: ['no cook', 'quick', 'budget friendly', 'vegetarian'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
  },
  {
    title: 'Scrambled Eggs',
    description: 'Fluffy scrambled eggs with butter and a pinch of salt.',
    meal_type: 'breakfast',
    category: 'Eggs',
    ingredients: [
      { name: 'eggs', quantity: 2, unit: null },
      { name: 'butter', quantity: 1, unit: 'tsp' },
      { name: 'salt', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Beat eggs with salt.',
      'Melt butter in a pan over medium-low heat.',
      'Cook eggs slowly, stirring, until softly set.',
    ],
    tags: ['quick', 'high protein', 'low effort'],
    prep_time_minutes: 3,
    cook_time_minutes: 5,
  },
  {
    title: 'Boiled Eggs Breakfast Plate',
    description: 'Boiled eggs with toast soldiers and cherry tomatoes.',
    meal_type: 'breakfast',
    category: 'Eggs',
    ingredients: [
      { name: 'eggs', quantity: 2, unit: null },
      { name: 'bread', quantity: 1, unit: 'slice' },
      { name: 'cherry tomatoes', quantity: 5, unit: null },
    ],
    instructions: [
      'Boil eggs 7 minutes for jammy yolks.',
      'Toast bread and cut into strips.',
      'Serve eggs with toast and tomatoes.',
    ],
    tags: ['high protein', 'budget friendly'],
    prep_time_minutes: 2,
    cook_time_minutes: 8,
  },
  {
    title: 'Omelette with Vegetables',
    description: 'Quick omelette filled with bell pepper and spinach.',
    meal_type: 'breakfast',
    category: 'Eggs',
    ingredients: [
      { name: 'eggs', quantity: 2, unit: null },
      { name: 'bell pepper', quantity: 0.25, unit: null },
      { name: 'spinach', quantity: 0.5, unit: 'cup' },
      { name: 'cheese', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Sauté diced pepper until soft, add spinach.',
      'Pour beaten eggs over vegetables.',
      'Fold when set and sprinkle cheese inside.',
    ],
    tags: ['high protein', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 8,
  },
  {
    title: 'Egg and Avocado Toast',
    description: 'Toasted bread topped with avocado and a fried egg.',
    meal_type: 'breakfast',
    category: 'Toast',
    ingredients: [
      { name: 'bread', quantity: 1, unit: 'slice' },
      { name: 'avocado', quantity: 0.5, unit: null },
      { name: 'egg', quantity: 1, unit: null },
      { name: 'salt', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Toast bread until golden.',
      'Mash avocado with salt and spread on toast.',
      'Top with a fried or poached egg.',
    ],
    tags: ['high protein', 'quick'],
    prep_time_minutes: 5,
    cook_time_minutes: 5,
  },
  {
    title: 'Avocado Toast',
    description: 'Classic avocado toast with lemon and chili flakes.',
    meal_type: 'breakfast',
    category: 'Toast',
    ingredients: [
      { name: 'bread', quantity: 1, unit: 'slice' },
      { name: 'avocado', quantity: 0.5, unit: null },
      { name: 'lemon juice', quantity: 1, unit: 'tsp' },
      { name: 'chili flakes', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Toast bread.',
      'Mash avocado with lemon and spread on toast.',
      'Finish with chili flakes.',
    ],
    tags: ['quick', 'vegetarian', 'no cook'],
    prep_time_minutes: 5,
    cook_time_minutes: 2,
  },
  {
    title: 'Peanut Butter Banana Toast',
    description: 'Filling toast with peanut butter and banana slices.',
    meal_type: 'breakfast',
    category: 'Toast',
    ingredients: [
      { name: 'bread', quantity: 1, unit: 'slice' },
      { name: 'peanut butter', quantity: 1, unit: 'tbsp' },
      { name: 'banana', quantity: 0.5, unit: null },
    ],
    instructions: [
      'Toast bread.',
      'Spread peanut butter and top with banana slices.',
    ],
    tags: ['quick', 'budget friendly', 'vegetarian'],
    prep_time_minutes: 3,
    cook_time_minutes: 2,
  },
  {
    title: 'Cereal with Milk',
    description: 'A simple bowl of cereal and cold milk.',
    meal_type: 'breakfast',
    category: 'Cereal',
    ingredients: [
      { name: 'cereal', quantity: 1, unit: 'cup' },
      { name: 'milk', quantity: 1, unit: 'cup' },
    ],
    instructions: [
      'Pour cereal into a bowl.',
      'Add milk and serve immediately.',
    ],
    tags: ['no cook', 'quick', 'budget friendly'],
    prep_time_minutes: 2,
    cook_time_minutes: 0,
  },
  {
    title: 'Granola with Milk',
    description: 'Crunchy granola with milk and optional fruit.',
    meal_type: 'breakfast',
    category: 'Cereal',
    ingredients: [
      { name: 'granola', quantity: 0.75, unit: 'cup' },
      { name: 'milk', quantity: 1, unit: 'cup' },
      { name: 'banana', quantity: 0.5, unit: null },
    ],
    instructions: [
      'Add granola to a bowl.',
      'Pour milk over and top with banana if desired.',
    ],
    tags: ['no cook', 'quick', 'vegetarian'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
  },
  {
    title: 'Banana Smoothie',
    description: 'Creamy banana smoothie with milk and yogurt.',
    meal_type: 'breakfast',
    category: 'Smoothie',
    ingredients: [
      { name: 'banana', quantity: 1, unit: null },
      { name: 'milk', quantity: 1, unit: 'cup' },
      { name: 'yogurt', quantity: 0.25, unit: 'cup' },
      { name: 'honey', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Blend all ingredients until smooth.',
      'Serve chilled.',
    ],
    tags: ['no cook', 'quick', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Green Smoothie',
    description: 'Spinach and fruit smoothie for a light morning boost.',
    meal_type: 'breakfast',
    category: 'Smoothie',
    ingredients: [
      { name: 'spinach', quantity: 1, unit: 'cup' },
      { name: 'banana', quantity: 1, unit: null },
      { name: 'apple', quantity: 0.5, unit: null },
      { name: 'water', quantity: 1, unit: 'cup' },
    ],
    instructions: [
      'Blend spinach, banana, apple, and water until smooth.',
      'Adjust thickness with more water if needed.',
    ],
    tags: ['no cook', 'vegetarian', 'vegan'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Berry Oatmeal',
    description: 'Oatmeal topped with mixed berries and a touch of maple syrup.',
    meal_type: 'breakfast',
    category: 'Oats',
    ingredients: [
      { name: 'rolled oats', quantity: 0.5, unit: 'cup' },
      { name: 'milk', quantity: 1, unit: 'cup' },
      { name: 'mixed berries', quantity: 0.5, unit: 'cup' },
      { name: 'maple syrup', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Cook oats with milk until creamy.',
      'Top with berries and maple syrup.',
    ],
    tags: ['vegetarian', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 5,
  },
  {
    title: 'Cottage Cheese Bowl',
    description: 'High-protein cottage cheese with fruit and seeds.',
    meal_type: 'breakfast',
    category: 'Yogurt Bowl',
    ingredients: [
      { name: 'cottage cheese', quantity: 1, unit: 'cup' },
      { name: 'peach', quantity: 1, unit: null },
      { name: 'pumpkin seeds', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Spoon cottage cheese into a bowl.',
      'Top with diced peach and pumpkin seeds.',
    ],
    tags: ['high protein', 'no cook', 'quick'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
]);
