import { defineBaseRecipes } from './helpers';

export const dinnerBaseRecipes = defineBaseRecipes('0003', [
  {
    title: 'Vegetable Omelette',
    description: 'Light dinner omelette with mushrooms and spinach.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'eggs', quantity: 3, unit: null },
      { name: 'mushrooms', quantity: 0.5, unit: 'cup' },
      { name: 'spinach', quantity: 1, unit: 'cup' },
      { name: 'cheese', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Sauté mushrooms and wilt spinach.',
      'Pour in beaten eggs and cook until set.',
      'Fold with cheese inside.',
    ],
    tags: ['quick', 'vegetarian', 'high protein'],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
  },
  {
    title: 'Soup and Toast',
    description: 'Warm soup with buttered toast for a simple dinner.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'vegetable soup', quantity: 2, unit: 'cups' },
      { name: 'bread', quantity: 2, unit: 'slices' },
      { name: 'butter', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Heat soup in a pot.',
      'Toast bread and spread with butter.',
      'Serve soup alongside toast.',
    ],
    tags: ['quick', 'low effort', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
  },
  {
    title: 'Tuna Salad Plate',
    description: 'Tuna salad plate with boiled egg and crackers.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'canned tuna', quantity: 1, unit: 'can' },
      { name: 'egg', quantity: 1, unit: null },
      { name: 'mixed greens', quantity: 2, unit: 'cups' },
      { name: 'crackers', quantity: 6, unit: null },
    ],
    instructions: [
      'Boil egg and arrange greens on a plate.',
      'Top with tuna and halved egg.',
      'Serve with crackers.',
    ],
    tags: ['no cook', 'high protein', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 8,
  },
  {
    title: 'Egg Salad Plate',
    description: 'Creamy egg salad with cucumber and bread.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'eggs', quantity: 3, unit: null },
      { name: 'mayonnaise', quantity: 2, unit: 'tbsp' },
      { name: 'cucumber', quantity: 0.5, unit: null },
      { name: 'bread', quantity: 2, unit: 'slices' },
    ],
    instructions: [
      'Boil eggs, chop, and mix with mayo.',
      'Serve with sliced cucumber and bread.',
    ],
    tags: ['vegetarian', 'budget friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 10,
  },
  {
    title: 'Hummus Plate',
    description: 'Hummus with pita, carrots, and cucumber sticks.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'hummus', quantity: 0.5, unit: 'cup' },
      { name: 'pita bread', quantity: 1, unit: null },
      { name: 'carrot', quantity: 1, unit: null },
      { name: 'cucumber', quantity: 0.5, unit: null },
    ],
    instructions: [
      'Warm pita and cut vegetables into sticks.',
      'Serve hummus as a dip with pita and veg.',
    ],
    tags: ['vegetarian', 'vegan', 'no cook', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
  },
  {
    title: 'Avocado Egg Toast',
    description: 'Avocado toast topped with soft-boiled eggs.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'bread', quantity: 2, unit: 'slices' },
      { name: 'avocado', quantity: 1, unit: null },
      { name: 'eggs', quantity: 2, unit: null },
      { name: 'salt', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Toast bread and mash avocado on top.',
      'Boil eggs 6 minutes and halve over toast.',
    ],
    tags: ['high protein', 'quick'],
    prep_time_minutes: 5,
    cook_time_minutes: 8,
  },
  {
    title: 'Grilled Chicken with Salad',
    description: 'Grilled chicken breast with a fresh side salad.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'chicken breast', quantity: 200, unit: 'g' },
      { name: 'mixed greens', quantity: 2, unit: 'cups' },
      { name: 'tomato', quantity: 1, unit: null },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Season and grill chicken until cooked.',
      'Toss salad with olive oil and serve alongside.',
    ],
    tags: ['high protein', 'meal prep friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
  },
  {
    title: 'Fish with Vegetables',
    description: 'Baked white fish with roasted mixed vegetables.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'white fish fillet', quantity: 200, unit: 'g' },
      { name: 'zucchini', quantity: 1, unit: null },
      { name: 'bell pepper', quantity: 1, unit: null },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Roast chopped vegetables with oil.',
      'Add fish to the tray and bake until flaky.',
    ],
    tags: ['high protein', 'one pot'],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
  },
  {
    title: 'Salmon with Vegetables',
    description: 'Pan-seared salmon with asparagus and lemon.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'salmon fillet', quantity: 200, unit: 'g' },
      { name: 'asparagus', quantity: 8, unit: 'spears' },
      { name: 'lemon', quantity: 0.5, unit: null },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Sear salmon skin-side down until crisp.',
      'Sauté asparagus and finish with lemon.',
    ],
    tags: ['high protein'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
  },
  {
    title: 'Chicken Stir Fry',
    description: 'Fast chicken stir fry with broccoli and ginger.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'chicken breast', quantity: 250, unit: 'g' },
      { name: 'broccoli', quantity: 2, unit: 'cups' },
      { name: 'ginger', quantity: 1, unit: 'tsp' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Stir-fry chicken until golden.',
      'Add broccoli, ginger, and soy sauce.',
      'Cook until tender-crisp.',
    ],
    tags: ['quick', 'high protein'],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
  },
  {
    title: 'Tofu Stir Fry',
    description: 'Crispy tofu stir fry with peppers and rice.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'firm tofu', quantity: 200, unit: 'g' },
      { name: 'bell pepper', quantity: 1, unit: null },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Pan-fry tofu cubes until golden.',
      'Stir-fry pepper, add tofu and soy sauce.',
      'Serve over rice.',
    ],
    tags: ['vegetarian', 'vegan', 'high protein'],
    prep_time_minutes: 15,
    cook_time_minutes: 20,
  },
  {
    title: 'Baked Potato with Tuna',
    description: 'Loaded baked potato with tuna and corn.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'potato', quantity: 1, unit: 'large' },
      { name: 'canned tuna', quantity: 1, unit: 'can' },
      { name: 'corn', quantity: 0.25, unit: 'cup' },
      { name: 'yogurt', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Bake potato until soft.',
      'Mix tuna, corn, and yogurt; spoon into potato.',
    ],
    tags: ['high protein', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 45,
  },
  {
    title: 'Baked Potato with Beans',
    description: 'Vegetarian baked potato topped with black beans and salsa.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'potato', quantity: 1, unit: 'large' },
      { name: 'black beans', quantity: 0.5, unit: 'can' },
      { name: 'salsa', quantity: 2, unit: 'tbsp' },
      { name: 'cheese', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Bake potato until tender.',
      'Warm beans and top potato with beans, salsa, and cheese.',
    ],
    tags: ['vegetarian', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 45,
  },
  {
    title: 'Chicken Quesadilla',
    description: 'Cheesy chicken quesadilla with salsa on the side.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'tortilla', quantity: 2, unit: null },
      { name: 'chicken breast', quantity: 150, unit: 'g' },
      { name: 'cheese', quantity: 0.5, unit: 'cup' },
      { name: 'salsa', quantity: 0.25, unit: 'cup' },
    ],
    instructions: [
      'Cook and shred chicken.',
      'Fill tortillas with chicken and cheese; pan-fry until melted.',
      'Serve with salsa.',
    ],
    tags: ['quick', 'high protein'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
  },
  {
    title: 'Veggie Quesadilla',
    description: 'Cheese and vegetable quesadilla with bell peppers.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'tortilla', quantity: 2, unit: null },
      { name: 'bell pepper', quantity: 1, unit: null },
      { name: 'cheese', quantity: 0.5, unit: 'cup' },
      { name: 'spinach', quantity: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Sauté pepper and spinach briefly.',
      'Fill tortillas with vegetables and cheese; cook until golden.',
    ],
    tags: ['vegetarian', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
  },
  {
    title: 'Pasta with Tomato Sauce',
    description: 'Simple spaghetti with homemade-style tomato sauce.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'spaghetti', quantity: 100, unit: 'g' },
      { name: 'tomato sauce', quantity: 1.5, unit: 'cups' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'parmesan', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Boil pasta until al dente.',
      'Warm sauce with garlic and toss with pasta.',
      'Top with parmesan.',
    ],
    tags: ['vegetarian', 'budget friendly', 'one pot'],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
  },
  {
    title: 'Pesto Pasta Dinner',
    description: 'Filling pesto pasta with pine nuts and parmesan.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'pasta', quantity: 100, unit: 'g' },
      { name: 'pesto', quantity: 3, unit: 'tbsp' },
      { name: 'pine nuts', quantity: 2, unit: 'tbsp' },
      { name: 'parmesan', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook pasta and reserve cooking water.',
      'Toss with pesto, pine nuts, and parmesan.',
    ],
    tags: ['vegetarian', 'quick'],
    prep_time_minutes: 5,
    cook_time_minutes: 12,
  },
  {
    title: 'Chickpea Stew',
    description: 'Warming chickpea and tomato stew for a cozy dinner.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'chickpeas', quantity: 1, unit: 'can' },
      { name: 'canned tomatoes', quantity: 1, unit: 'can' },
      { name: 'spinach', quantity: 2, unit: 'cups' },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Simmer chickpeas with tomatoes and cumin.',
      'Stir in spinach until wilted.',
    ],
    tags: ['vegetarian', 'vegan', 'one pot', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 20,
  },
  {
    title: 'Lentil Bowl',
    description: 'Brown lentils over rice with roasted vegetables.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'brown lentils', quantity: 1, unit: 'cup' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'carrot', quantity: 2, unit: null },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook lentils and rice separately.',
      'Roast diced carrots; assemble bowl.',
    ],
    tags: ['vegetarian', 'vegan', 'meal prep friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 35,
  },
  {
    title: 'Rice Bowl Leftovers',
    description: 'Transform leftover rice and vegetables into a quick bowl.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'cooked rice', quantity: 2, unit: 'cups' },
      { name: 'mixed vegetables', quantity: 1, unit: 'cup' },
      { name: 'soy sauce', quantity: 1, unit: 'tbsp' },
      { name: 'egg', quantity: 1, unit: null },
    ],
    instructions: [
      'Stir-fry rice with vegetables and soy sauce.',
      'Top with a fried egg.',
    ],
    tags: ['uses leftovers', 'quick', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
  },
  {
    title: 'Shrimp Pasta',
    description: 'Garlic shrimp tossed with linguine and parsley.',
    meal_type: 'dinner',
    category: 'Dinner Main',
    ingredients: [
      { name: 'shrimp', quantity: 200, unit: 'g' },
      { name: 'linguine', quantity: 100, unit: 'g' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'parsley', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook pasta.',
      'Sauté shrimp with garlic; toss with pasta and parsley.',
    ],
    tags: ['high protein', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    difficulty: 'medium',
  },
  {
    title: 'Minestrone Soup',
    description: 'Italian vegetable soup with beans and pasta.',
    meal_type: 'dinner',
    category: 'Light Dinner',
    ingredients: [
      { name: 'cannellini beans', quantity: 1, unit: 'can' },
      { name: 'small pasta', quantity: 0.5, unit: 'cup' },
      { name: 'zucchini', quantity: 1, unit: null },
      { name: 'vegetable broth', quantity: 4, unit: 'cups' },
    ],
    instructions: [
      'Simmer vegetables in broth.',
      'Add beans and pasta; cook until pasta is tender.',
    ],
    tags: ['vegetarian', 'one pot', 'freezer friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
  },
]);
