import { defineBaseRecipes } from './helpers';

export const inspirationBaseRecipes = defineBaseRecipes('0005', [
  {
    title: 'Classic Beef Burger',
    description: 'Juicy beef patty on a toasted bun with lettuce, tomato, and cheese.',
    meal_type: 'lunch',
    category: 'Burgers',
    ingredients: [
      { name: 'ground beef', quantity: 150, unit: 'g' },
      { name: 'burger bun', quantity: 1, unit: null },
      { name: 'cheddar cheese', quantity: 1, unit: 'slice' },
      { name: 'lettuce', quantity: 2, unit: 'leaves' },
      { name: 'tomato', quantity: 2, unit: 'slices' },
    ],
    instructions: [
      'Season beef and form into a patty.',
      'Pan-sear patty 4 minutes per side until cooked through.',
      'Toast bun, add cheese to melt on the patty, then assemble with lettuce and tomato.',
    ],
    tags: ['high protein', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
  },
  {
    title: 'Mediterranean Grain Bowl',
    description: 'Quinoa bowl with cucumber, tomato, chickpeas, and lemon dressing.',
    meal_type: 'lunch',
    category: 'Healthy',
    ingredients: [
      { name: 'quinoa', quantity: 0.5, unit: 'cup' },
      { name: 'chickpeas', quantity: 0.5, unit: 'cup' },
      { name: 'cucumber', quantity: 0.5, unit: null },
      { name: 'cherry tomatoes', quantity: 0.5, unit: 'cup' },
      { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook quinoa and let cool slightly.',
      'Dice cucumber and halve tomatoes.',
      'Combine quinoa, chickpeas, and vegetables; drizzle with lemon juice.',
    ],
    tags: ['vegetarian', 'meal prep friendly', 'high protein'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
  },
  {
    title: 'Vegetable Stir-Fry with Rice',
    description: 'Colorful mixed vegetables stir-fried and served over steamed rice.',
    meal_type: 'lunch',
    category: 'Oriental',
    ingredients: [
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'broccoli', quantity: 1, unit: 'cup' },
      { name: 'bell pepper', quantity: 1, unit: null },
      { name: 'carrot', quantity: 1, unit: null },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook rice according to package directions.',
      'Stir-fry chopped vegetables in a hot pan until tender-crisp.',
      'Add soy sauce, toss, and serve over rice.',
    ],
    tags: ['vegetarian', 'quick', 'budget friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
  },
  {
    title: 'Lemon Herb Chicken',
    description: 'Pan-roasted chicken breast with lemon, garlic, and fresh herbs.',
    meal_type: 'dinner',
    category: 'Chicken',
    ingredients: [
      { name: 'chicken breast', quantity: 200, unit: 'g' },
      { name: 'lemon', quantity: 0.5, unit: null },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'parsley', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Season chicken with salt and pepper.',
      'Sear in olive oil until golden, then reduce heat and cook through.',
      'Squeeze lemon over chicken, add garlic and parsley, and rest before serving.',
    ],
    tags: ['high protein', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 18,
  },
  {
    title: 'Pan-Seared Steak with Vegetables',
    description: 'Simple steak dinner with sautéed green beans and potatoes.',
    meal_type: 'dinner',
    category: 'Meat',
    ingredients: [
      { name: 'sirloin steak', quantity: 200, unit: 'g' },
      { name: 'potato', quantity: 2, unit: null },
      { name: 'green beans', quantity: 1, unit: 'cup' },
      { name: 'butter', quantity: 1, unit: 'tbsp' },
      { name: 'garlic', quantity: 1, unit: 'clove' },
    ],
    instructions: [
      'Boil potatoes until tender; season and lightly crush.',
      'Sear steak to desired doneness and rest before slicing.',
      'Sauté green beans in butter and garlic; serve with steak and potatoes.',
    ],
    tags: ['high protein'],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    difficulty: 'medium',
  },
  {
    title: 'Weekend Breakfast Plate',
    description: 'Scrambled eggs, buttered toast, and fresh fruit for a hearty morning meal.',
    meal_type: 'breakfast',
    category: 'Breakfast',
    ingredients: [
      { name: 'eggs', quantity: 2, unit: null },
      { name: 'bread', quantity: 2, unit: 'slices' },
      { name: 'butter', quantity: 1, unit: 'tbsp' },
      { name: 'berries', quantity: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Scramble eggs in a nonstick pan until softly set.',
      'Toast bread and spread with butter.',
      'Plate eggs and toast with a side of berries.',
    ],
    tags: ['quick', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
  },
  {
    title: 'Teriyaki Chicken Rice Bowl',
    description: 'Glazed teriyaki chicken over rice with steamed broccoli.',
    meal_type: 'lunch',
    category: 'Asian',
    ingredients: [
      { name: 'chicken breast', quantity: 150, unit: 'g' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'broccoli', quantity: 1, unit: 'cup' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
      { name: 'honey', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook rice according to package directions.',
      'Pan-sear diced chicken; add soy sauce and honey to glaze.',
      'Steam broccoli and assemble bowl.',
    ],
    tags: ['high protein', 'meal prep friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
  },
  {
    title: 'Berry Yogurt Parfait',
    description: 'Layered Greek yogurt with mixed berries and a drizzle of honey.',
    meal_type: 'snack',
    category: 'Dessert',
    ingredients: [
      { name: 'greek yogurt', quantity: 0.75, unit: 'cup' },
      { name: 'mixed berries', quantity: 0.5, unit: 'cup' },
      { name: 'honey', quantity: 1, unit: 'tbsp' },
      { name: 'granola', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Layer yogurt, berries, and granola in a glass.',
      'Drizzle honey on top and serve chilled.',
    ],
    tags: ['no cook', 'quick', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Caprese Pasta',
    description: 'Pasta tossed with fresh tomatoes, mozzarella, and basil.',
    meal_type: 'lunch',
    category: 'Italian',
    ingredients: [
      { name: 'pasta', quantity: 100, unit: 'g' },
      { name: 'cherry tomatoes', quantity: 1, unit: 'cup' },
      { name: 'mozzarella', quantity: 100, unit: 'g' },
      { name: 'fresh basil', quantity: 0.25, unit: 'cup' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Boil pasta until al dente; drain and cool slightly.',
      'Halve tomatoes and tear mozzarella.',
      'Toss pasta with tomatoes, mozzarella, basil, and olive oil.',
    ],
    tags: ['vegetarian', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
  },
]);
