import { defineBaseRecipes } from './helpers';

export const lunchBaseRecipes = defineBaseRecipes('0002', [
  {
    title: 'Chicken Rice Bowl',
    description: 'Seasoned chicken over rice with steamed vegetables.',
    meal_type: 'lunch',
    category: 'Rice Bowl',
    ingredients: [
      { name: 'chicken breast', quantity: 150, unit: 'g' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'broccoli', quantity: 1, unit: 'cup' },
      { name: 'soy sauce', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook rice according to package directions.',
      'Pan-sear diced chicken until cooked through.',
      'Steam broccoli and assemble bowl with soy sauce.',
    ],
    tags: ['high protein', 'meal prep friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
  },
  {
    title: 'Beef Rice Bowl',
    description: 'Savory ground beef over rice with onions and peppers.',
    meal_type: 'lunch',
    category: 'Rice Bowl',
    ingredients: [
      { name: 'ground beef', quantity: 150, unit: 'g' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'onion', quantity: 0.5, unit: null },
      { name: 'bell pepper', quantity: 0.5, unit: null },
    ],
    instructions: [
      'Cook rice.',
      'Brown beef with diced onion and pepper.',
      'Serve beef mixture over rice.',
    ],
    tags: ['high protein', 'budget friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
  },
  {
    title: 'Tuna Rice Bowl',
    description: 'Quick tuna and rice bowl with cucumber and soy sauce.',
    meal_type: 'lunch',
    category: 'Rice Bowl',
    ingredients: [
      { name: 'canned tuna', quantity: 1, unit: 'can' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'cucumber', quantity: 0.5, unit: null },
      { name: 'soy sauce', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook rice and flake tuna into a bowl.',
      'Slice cucumber and add on top.',
      'Drizzle with soy sauce.',
    ],
    tags: ['quick', 'high protein', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
  },
  {
    title: 'Egg Fried Rice',
    description: 'Classic fried rice with eggs and frozen peas.',
    meal_type: 'lunch',
    category: 'Rice Bowl',
    ingredients: [
      { name: 'cooked rice', quantity: 2, unit: 'cups' },
      { name: 'eggs', quantity: 2, unit: null },
      { name: 'frozen peas', quantity: 0.5, unit: 'cup' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Scramble eggs in a hot pan and set aside.',
      'Stir-fry rice and peas until heated.',
      'Return eggs, add soy sauce, and toss.',
    ],
    tags: ['uses leftovers', 'budget friendly', 'quick'],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
  },
  {
    title: 'Vegetable Rice Bowl',
    description: 'Colorful vegetable rice bowl with sesame oil.',
    meal_type: 'lunch',
    category: 'Rice Bowl',
    ingredients: [
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'carrot', quantity: 1, unit: null },
      { name: 'zucchini', quantity: 1, unit: null },
      { name: 'sesame oil', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Cook rice.',
      'Sauté diced vegetables until tender.',
      'Combine with rice and sesame oil.',
    ],
    tags: ['vegetarian', 'vegan', 'budget friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
  },
  {
    title: 'Chickpea Rice Bowl',
    description: 'Spiced chickpeas over rice with lemon and herbs.',
    meal_type: 'lunch',
    category: 'Rice Bowl',
    ingredients: [
      { name: 'chickpeas', quantity: 1, unit: 'can' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
      { name: 'parsley', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Warm chickpeas with spices in a pan.',
      'Serve over cooked rice with lemon and parsley.',
    ],
    tags: ['vegetarian', 'vegan', 'budget friendly', 'meal prep friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
  },
  {
    title: 'Tomato Pasta',
    description: 'Simple pasta with tomato sauce and garlic.',
    meal_type: 'lunch',
    category: 'Pasta',
    ingredients: [
      { name: 'pasta', quantity: 100, unit: 'g' },
      { name: 'tomato sauce', quantity: 1, unit: 'cup' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Boil pasta until al dente.',
      'Warm tomato sauce with minced garlic and olive oil.',
      'Toss pasta with sauce and serve.',
    ],
    tags: ['budget friendly', 'vegetarian', 'one pot'],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
  },
  {
    title: 'Tuna Pasta',
    description: 'Quick tuna pasta with capers and lemon.',
    meal_type: 'lunch',
    category: 'Pasta',
    ingredients: [
      { name: 'pasta', quantity: 100, unit: 'g' },
      { name: 'canned tuna', quantity: 1, unit: 'can' },
      { name: 'lemon juice', quantity: 1, unit: 'tbsp' },
      { name: 'capers', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook pasta and reserve a little cooking water.',
      'Mix tuna, lemon, and capers with pasta.',
      'Loosen with pasta water if needed.',
    ],
    tags: ['quick', 'high protein'],
    prep_time_minutes: 5,
    cook_time_minutes: 12,
  },
  {
    title: 'Chicken Pasta',
    description: 'Chicken pieces tossed with pasta and olive oil.',
    meal_type: 'lunch',
    category: 'Pasta',
    ingredients: [
      { name: 'pasta', quantity: 100, unit: 'g' },
      { name: 'chicken breast', quantity: 150, unit: 'g' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
      { name: 'parmesan', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook pasta and sauté diced chicken until golden.',
      'Toss together with olive oil and parmesan.',
    ],
    tags: ['high protein'],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
  },
  {
    title: 'Pesto Pasta',
    description: 'Bright pesto pasta with cherry tomatoes.',
    meal_type: 'lunch',
    category: 'Pasta',
    ingredients: [
      { name: 'pasta', quantity: 100, unit: 'g' },
      { name: 'pesto', quantity: 3, unit: 'tbsp' },
      { name: 'cherry tomatoes', quantity: 0.5, unit: 'cup' },
      { name: 'parmesan', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook pasta and halve tomatoes.',
      'Toss hot pasta with pesto and tomatoes.',
      'Top with parmesan.',
    ],
    tags: ['quick', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 12,
  },
  {
    title: 'Vegetable Pasta',
    description: 'Pasta with sautéed seasonal vegetables.',
    meal_type: 'lunch',
    category: 'Pasta',
    ingredients: [
      { name: 'pasta', quantity: 100, unit: 'g' },
      { name: 'zucchini', quantity: 1, unit: null },
      { name: 'bell pepper', quantity: 1, unit: null },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Boil pasta.',
      'Sauté diced vegetables in olive oil.',
      'Combine and season to taste.',
    ],
    tags: ['vegetarian', 'budget friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
  },
  {
    title: 'Vegetable Soup',
    description: 'Light vegetable soup with carrots, celery, and potato.',
    meal_type: 'lunch',
    category: 'Soup',
    ingredients: [
      { name: 'carrot', quantity: 2, unit: null },
      { name: 'celery', quantity: 2, unit: 'stalks' },
      { name: 'potato', quantity: 1, unit: null },
      { name: 'vegetable broth', quantity: 4, unit: 'cups' },
    ],
    instructions: [
      'Dice vegetables and simmer in broth 20 minutes.',
      'Season with salt and pepper.',
    ],
    tags: ['vegetarian', 'vegan', 'one pot', 'freezer friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
  },
  {
    title: 'Chicken Soup',
    description: 'Comforting chicken soup with noodles.',
    meal_type: 'lunch',
    category: 'Soup',
    ingredients: [
      { name: 'chicken breast', quantity: 200, unit: 'g' },
      { name: 'egg noodles', quantity: 100, unit: 'g' },
      { name: 'carrot', quantity: 1, unit: null },
      { name: 'chicken broth', quantity: 4, unit: 'cups' },
    ],
    instructions: [
      'Simmer chicken in broth until cooked, then shred.',
      'Add diced carrot and noodles; cook until tender.',
    ],
    tags: ['high protein', 'one pot', 'freezer friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
  },
  {
    title: 'Lentil Soup',
    description: 'Hearty red lentil soup with cumin and lemon.',
    meal_type: 'lunch',
    category: 'Soup',
    ingredients: [
      { name: 'red lentils', quantity: 1, unit: 'cup' },
      { name: 'onion', quantity: 1, unit: null },
      { name: 'cumin', quantity: 1, unit: 'tsp' },
      { name: 'vegetable broth', quantity: 4, unit: 'cups' },
    ],
    instructions: [
      'Sauté onion with cumin.',
      'Add lentils and broth; simmer until soft.',
      'Blend partially for a creamy texture.',
    ],
    tags: ['vegetarian', 'vegan', 'budget friendly', 'one pot'],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
  },
  {
    title: 'Tomato Soup',
    description: 'Smooth tomato soup with basil.',
    meal_type: 'lunch',
    category: 'Soup',
    ingredients: [
      { name: 'canned tomatoes', quantity: 1, unit: 'can' },
      { name: 'onion', quantity: 0.5, unit: null },
      { name: 'vegetable broth', quantity: 2, unit: 'cups' },
      { name: 'basil', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Sauté onion, add tomatoes and broth.',
      'Simmer 15 minutes and blend smooth.',
      'Stir in basil before serving.',
    ],
    tags: ['vegetarian', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 20,
  },
  {
    title: 'Chicken Salad',
    description: 'Chicken salad with lettuce, cucumber, and vinaigrette.',
    meal_type: 'lunch',
    category: 'Salad',
    ingredients: [
      { name: 'chicken breast', quantity: 150, unit: 'g' },
      { name: 'lettuce', quantity: 2, unit: 'cups' },
      { name: 'cucumber', quantity: 0.5, unit: null },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook and slice chicken.',
      'Toss lettuce and cucumber with olive oil and lemon.',
      'Top with chicken.',
    ],
    tags: ['high protein', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
  },
  {
    title: 'Tuna Salad',
    description: 'Classic tuna salad with mixed greens.',
    meal_type: 'lunch',
    category: 'Salad',
    ingredients: [
      { name: 'canned tuna', quantity: 1, unit: 'can' },
      { name: 'mixed greens', quantity: 2, unit: 'cups' },
      { name: 'tomato', quantity: 1, unit: null },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Arrange greens on a plate.',
      'Top with flaked tuna and sliced tomato.',
      'Dress with olive oil.',
    ],
    tags: ['quick', 'high protein', 'no cook'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Chickpea Salad',
    description: 'Chickpea salad with tomato, cucumber, and feta.',
    meal_type: 'lunch',
    category: 'Salad',
    ingredients: [
      { name: 'chickpeas', quantity: 1, unit: 'can' },
      { name: 'tomato', quantity: 1, unit: null },
      { name: 'cucumber', quantity: 0.5, unit: null },
      { name: 'feta cheese', quantity: 50, unit: 'g' },
    ],
    instructions: [
      'Drain chickpeas and dice vegetables.',
      'Combine and crumble feta on top.',
    ],
    tags: ['vegetarian', 'meal prep friendly', 'no cook'],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
  },
  {
    title: 'Greek Salad',
    description: 'Tomato, cucumber, olives, and feta with oregano.',
    meal_type: 'lunch',
    category: 'Salad',
    ingredients: [
      { name: 'tomato', quantity: 2, unit: null },
      { name: 'cucumber', quantity: 1, unit: null },
      { name: 'feta cheese', quantity: 80, unit: 'g' },
      { name: 'olives', quantity: 0.25, unit: 'cup' },
    ],
    instructions: [
      'Chop vegetables and combine in a bowl.',
      'Add olives, feta, olive oil, and oregano.',
    ],
    tags: ['vegetarian', 'no cook', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
  },
  {
    title: 'Chicken Wrap',
    description: 'Grilled chicken wrap with lettuce and yogurt sauce.',
    meal_type: 'lunch',
    category: 'Wrap',
    ingredients: [
      { name: 'tortilla', quantity: 1, unit: null },
      { name: 'chicken breast', quantity: 120, unit: 'g' },
      { name: 'lettuce', quantity: 0.5, unit: 'cup' },
      { name: 'yogurt', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cook and slice chicken.',
      'Spread yogurt on tortilla, add lettuce and chicken.',
      'Roll tightly and slice in half.',
    ],
    tags: ['high protein', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
  },
  {
    title: 'Tuna Wrap',
    description: 'Tuna wrap with crunchy celery and mayo.',
    meal_type: 'lunch',
    category: 'Wrap',
    ingredients: [
      { name: 'tortilla', quantity: 1, unit: null },
      { name: 'canned tuna', quantity: 1, unit: 'can' },
      { name: 'celery', quantity: 1, unit: 'stalk' },
      { name: 'mayonnaise', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Mix tuna, diced celery, and mayo.',
      'Spoon into tortilla and roll.',
    ],
    tags: ['quick', 'high protein', 'no cook'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Veggie Wrap',
    description: 'Hummus veggie wrap with roasted peppers.',
    meal_type: 'lunch',
    category: 'Wrap',
    ingredients: [
      { name: 'tortilla', quantity: 1, unit: null },
      { name: 'hummus', quantity: 3, unit: 'tbsp' },
      { name: 'bell pepper', quantity: 0.5, unit: null },
      { name: 'spinach', quantity: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Spread hummus on tortilla.',
      'Add sliced pepper and spinach, then roll.',
    ],
    tags: ['vegetarian', 'vegan', 'quick', 'no cook'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Chicken Sandwich',
    description: 'Simple chicken sandwich with lettuce and tomato.',
    meal_type: 'lunch',
    category: 'Sandwich',
    ingredients: [
      { name: 'bread', quantity: 2, unit: 'slices' },
      { name: 'chicken breast', quantity: 120, unit: 'g' },
      { name: 'lettuce', quantity: 2, unit: 'leaves' },
      { name: 'tomato', quantity: 2, unit: 'slices' },
    ],
    instructions: [
      'Cook chicken and slice.',
      'Layer lettuce, tomato, and chicken between bread slices.',
    ],
    tags: ['high protein'],
    prep_time_minutes: 5,
    cook_time_minutes: 12,
  },
  {
    title: 'Tuna Sandwich',
    description: 'Classic tuna sandwich on whole grain bread.',
    meal_type: 'lunch',
    category: 'Sandwich',
    ingredients: [
      { name: 'bread', quantity: 2, unit: 'slices' },
      { name: 'canned tuna', quantity: 1, unit: 'can' },
      { name: 'mayonnaise', quantity: 1, unit: 'tbsp' },
      { name: 'celery', quantity: 1, unit: 'stalk' },
    ],
    instructions: [
      'Mix tuna, mayo, and diced celery.',
      'Spread between bread slices.',
    ],
    tags: ['quick', 'budget friendly', 'no cook'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Chicken with Rice and Vegetables',
    description: 'Pan-roasted chicken with rice and mixed vegetables.',
    meal_type: 'lunch',
    category: 'Main Dish',
    ingredients: [
      { name: 'chicken thigh', quantity: 2, unit: null },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'mixed vegetables', quantity: 2, unit: 'cups' },
      { name: 'olive oil', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Roast chicken thighs until cooked through.',
      'Cook rice and steam vegetables.',
      'Plate together with a drizzle of olive oil.',
    ],
    tags: ['high protein', 'meal prep friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
  },
  {
    title: 'Chicken with Potatoes',
    description: 'Roasted chicken with herb potatoes.',
    meal_type: 'lunch',
    category: 'Main Dish',
    ingredients: [
      { name: 'chicken drumsticks', quantity: 2, unit: null },
      { name: 'potato', quantity: 2, unit: null },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'rosemary', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Toss potato wedges with oil and rosemary.',
      'Roast with chicken at 200°C for 35 minutes.',
    ],
    tags: ['high protein', 'one pot'],
    prep_time_minutes: 10,
    cook_time_minutes: 35,
    difficulty: 'medium',
  },
  {
    title: 'Beef with Rice',
    description: 'Simple beef strips with seasoned rice.',
    meal_type: 'lunch',
    category: 'Main Dish',
    ingredients: [
      { name: 'beef strips', quantity: 150, unit: 'g' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'soy sauce', quantity: 1, unit: 'tbsp' },
      { name: 'garlic', quantity: 2, unit: 'cloves' },
    ],
    instructions: [
      'Cook rice.',
      'Stir-fry beef with garlic and soy sauce.',
      'Serve over rice.',
    ],
    tags: ['high protein'],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
  },
  {
    title: 'Fish with Rice',
    description: 'Pan-seared white fish with lemon rice.',
    meal_type: 'lunch',
    category: 'Main Dish',
    ingredients: [
      { name: 'white fish fillet', quantity: 150, unit: 'g' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'lemon', quantity: 0.5, unit: null },
      { name: 'butter', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Cook rice with lemon zest.',
      'Pan-sear fish with butter until flaky.',
      'Serve fish over rice with lemon wedges.',
    ],
    tags: ['high protein', 'quick'],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
  },
  {
    title: 'Chicken Curry',
    description: 'Mild chicken curry with coconut milk and rice.',
    meal_type: 'lunch',
    category: 'Main Dish',
    ingredients: [
      { name: 'chicken thigh', quantity: 300, unit: 'g' },
      { name: 'coconut milk', quantity: 1, unit: 'can' },
      { name: 'curry powder', quantity: 2, unit: 'tbsp' },
      { name: 'rice', quantity: 1, unit: 'cup' },
    ],
    instructions: [
      'Brown chicken, add curry powder.',
      'Pour in coconut milk and simmer 20 minutes.',
      'Serve with rice.',
    ],
    tags: ['meal prep friendly', 'one pot'],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    difficulty: 'medium',
  },
  {
    title: 'Chickpea Curry',
    description: 'Vegetarian chickpea curry with tomatoes.',
    meal_type: 'lunch',
    category: 'Main Dish',
    ingredients: [
      { name: 'chickpeas', quantity: 1, unit: 'can' },
      { name: 'canned tomatoes', quantity: 1, unit: 'can' },
      { name: 'curry powder', quantity: 1, unit: 'tbsp' },
      { name: 'rice', quantity: 1, unit: 'cup' },
    ],
    instructions: [
      'Simmer chickpeas with tomatoes and curry powder.',
      'Cook until thickened; serve with rice.',
    ],
    tags: ['vegetarian', 'vegan', 'budget friendly', 'one pot'],
    prep_time_minutes: 5,
    cook_time_minutes: 20,
  },
  {
    title: 'Lentil Stew',
    description: 'Thick lentil stew with carrots and spices.',
    meal_type: 'lunch',
    category: 'Main Dish',
    ingredients: [
      { name: 'brown lentils', quantity: 1, unit: 'cup' },
      { name: 'carrot', quantity: 2, unit: null },
      { name: 'onion', quantity: 1, unit: null },
      { name: 'vegetable broth', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Sauté onion and carrot.',
      'Add lentils and broth; simmer until tender.',
    ],
    tags: ['vegetarian', 'vegan', 'budget friendly', 'freezer friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 35,
  },
  {
    title: 'Stir Fry Chicken',
    description: 'Quick chicken stir fry with vegetables and soy sauce.',
    meal_type: 'lunch',
    category: 'Main Dish',
    ingredients: [
      { name: 'chicken breast', quantity: 200, unit: 'g' },
      { name: 'broccoli', quantity: 1, unit: 'cup' },
      { name: 'bell pepper', quantity: 1, unit: null },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Stir-fry chicken until nearly cooked.',
      'Add vegetables and soy sauce.',
      'Cook until crisp-tender.',
    ],
    tags: ['quick', 'high protein'],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
  },
  {
    title: 'Burrito Bowl',
    description: 'Rice bowl with beans, corn, salsa, and lettuce.',
    meal_type: 'lunch',
    category: 'Rice Bowl',
    ingredients: [
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'black beans', quantity: 1, unit: 'can' },
      { name: 'corn', quantity: 0.5, unit: 'cup' },
      { name: 'salsa', quantity: 0.25, unit: 'cup' },
    ],
    instructions: [
      'Cook rice and warm beans with corn.',
      'Assemble bowl with lettuce and salsa on top.',
    ],
    tags: ['vegetarian', 'meal prep friendly', 'budget friendly'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
  },
  {
    title: 'Turkey Sandwich',
    description: 'Lean turkey sandwich with mustard and greens.',
    meal_type: 'lunch',
    category: 'Sandwich',
    ingredients: [
      { name: 'bread', quantity: 2, unit: 'slices' },
      { name: 'turkey slices', quantity: 100, unit: 'g' },
      { name: 'mustard', quantity: 1, unit: 'tsp' },
      { name: 'lettuce', quantity: 2, unit: 'leaves' },
    ],
    instructions: [
      'Spread mustard on bread.',
      'Layer turkey and lettuce; close sandwich.',
    ],
    tags: ['quick', 'high protein', 'no cook'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
]);
