import { defineBaseRecipes } from './helpers';

export const snackBaseRecipes = defineBaseRecipes('0004', [
  {
    title: 'Apple with Peanut Butter',
    description: 'Sliced apple with a side of peanut butter for dipping.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'apple', quantity: 1, unit: null },
      { name: 'peanut butter', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Slice apple into wedges.',
      'Serve with peanut butter for dipping.',
    ],
    tags: ['no cook', 'quick', 'vegetarian'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
  },
  {
    title: 'Banana with Peanut Butter',
    description: 'Banana halves spread with peanut butter.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'banana', quantity: 1, unit: null },
      { name: 'peanut butter', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Halve banana lengthwise.',
      'Spread peanut butter on each half.',
    ],
    tags: ['no cook', 'quick', 'budget friendly'],
    prep_time_minutes: 2,
    cook_time_minutes: 0,
  },
  {
    title: 'Greek Yogurt Snack',
    description: 'Greek yogurt with honey and a sprinkle of cinnamon.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'greek yogurt', quantity: 0.75, unit: 'cup' },
      { name: 'honey', quantity: 1, unit: 'tsp' },
      { name: 'cinnamon', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Spoon yogurt into a bowl.',
      'Drizzle honey and sprinkle cinnamon.',
    ],
    tags: ['high protein', 'no cook', 'quick'],
    prep_time_minutes: 2,
    cook_time_minutes: 0,
  },
  {
    title: 'Nuts and Fruit',
    description: 'A handful of mixed nuts with dried or fresh fruit.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'mixed nuts', quantity: 0.25, unit: 'cup' },
      { name: 'dried apricots', quantity: 3, unit: null },
    ],
    instructions: [
      'Combine nuts and fruit in a small bowl.',
      'Enjoy as a portable snack.',
    ],
    tags: ['no cook', 'vegetarian', 'vegan'],
    prep_time_minutes: 2,
    cook_time_minutes: 0,
  },
  {
    title: 'Rice Cakes with Hummus',
    description: 'Crunchy rice cakes topped with hummus and cucumber.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'rice cakes', quantity: 2, unit: null },
      { name: 'hummus', quantity: 3, unit: 'tbsp' },
      { name: 'cucumber', quantity: 0.25, unit: null },
    ],
    instructions: [
      'Spread hummus on rice cakes.',
      'Top with thin cucumber slices.',
    ],
    tags: ['no cook', 'vegetarian', 'vegan', 'quick'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Toast with Peanut Butter',
    description: 'Simple toast with creamy peanut butter.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'bread', quantity: 1, unit: 'slice' },
      { name: 'peanut butter', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Toast bread until golden.',
      'Spread peanut butter and serve.',
    ],
    tags: ['quick', 'budget friendly'],
    prep_time_minutes: 2,
    cook_time_minutes: 2,
  },
  {
    title: 'Carrot Sticks with Hummus',
    description: 'Fresh carrot sticks with hummus dip.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'carrot', quantity: 2, unit: null },
      { name: 'hummus', quantity: 0.25, unit: 'cup' },
    ],
    instructions: [
      'Cut carrots into sticks.',
      'Serve with hummus for dipping.',
    ],
    tags: ['no cook', 'vegetarian', 'vegan', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Cheese and Crackers',
    description: 'Cheese slices with whole grain crackers.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'cheddar cheese', quantity: 50, unit: 'g' },
      { name: 'crackers', quantity: 8, unit: null },
    ],
    instructions: [
      'Slice cheese and arrange with crackers.',
    ],
    tags: ['no cook', 'quick'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
  },
  {
    title: 'Boiled Eggs Snack',
    description: 'Two boiled eggs with a pinch of salt and pepper.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'eggs', quantity: 2, unit: null },
      { name: 'salt', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Boil eggs 8 minutes for firm yolks.',
      'Peel, halve, and season.',
    ],
    tags: ['high protein', 'budget friendly'],
    prep_time_minutes: 2,
    cook_time_minutes: 8,
  },
  {
    title: 'Smoothie Snack',
    description: 'Small berry yogurt smoothie for an afternoon pick-me-up.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'berries', quantity: 0.5, unit: 'cup' },
      { name: 'yogurt', quantity: 0.5, unit: 'cup' },
      { name: 'milk', quantity: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Blend all ingredients until smooth.',
      'Serve immediately.',
    ],
    tags: ['no cook', 'quick', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Cottage Cheese Snack',
    description: 'Cottage cheese with pineapple chunks.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'cottage cheese', quantity: 0.75, unit: 'cup' },
      { name: 'pineapple', quantity: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Spoon cottage cheese into a bowl.',
      'Top with pineapple.',
    ],
    tags: ['high protein', 'no cook', 'quick'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
  },
  {
    title: 'Popcorn',
    description: 'Lightly salted stovetop or microwave popcorn.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'popcorn kernels', quantity: 0.25, unit: 'cup' },
      { name: 'oil', quantity: 1, unit: 'tbsp' },
      { name: 'salt', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Pop kernels in oil over medium heat.',
      'Season with salt and serve warm.',
    ],
    tags: ['budget friendly', 'vegan'],
    prep_time_minutes: 2,
    cook_time_minutes: 5,
  },
  {
    title: 'Trail Mix',
    description: 'Homemade trail mix with nuts, seeds, and raisins.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'almonds', quantity: 0.25, unit: 'cup' },
      { name: 'pumpkin seeds', quantity: 2, unit: 'tbsp' },
      { name: 'raisins', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Mix all ingredients in a small container.',
      'Portion for on-the-go snacking.',
    ],
    tags: ['no cook', 'vegetarian', 'vegan', 'meal prep friendly'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
  },
  {
    title: 'Granola Bar',
    description: 'Store-bought or homemade granola bar with fruit.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'granola bar', quantity: 1, unit: null },
      { name: 'apple', quantity: 0.5, unit: null },
    ],
    instructions: [
      'Unwrap granola bar and serve with apple slices.',
    ],
    tags: ['no cook', 'quick'],
    prep_time_minutes: 2,
    cook_time_minutes: 0,
  },
  {
    title: 'Fruit Bowl',
    description: 'Mixed seasonal fruit in a simple bowl.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'banana', quantity: 0.5, unit: null },
      { name: 'apple', quantity: 0.5, unit: null },
      { name: 'grapes', quantity: 0.5, unit: 'cup' },
    ],
    instructions: [
      'Chop fruit and combine in a bowl.',
      'Serve chilled.',
    ],
    tags: ['no cook', 'vegan', 'vegetarian'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
  {
    title: 'Edamame Snack',
    description: 'Steamed edamame pods with sea salt.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'frozen edamame', quantity: 1, unit: 'cup' },
      { name: 'sea salt', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Steam or microwave edamame until hot.',
      'Sprinkle with sea salt.',
    ],
    tags: ['high protein', 'vegetarian', 'vegan'],
    prep_time_minutes: 2,
    cook_time_minutes: 5,
  },
  {
    title: 'Celery with Peanut Butter',
    description: 'Celery sticks filled with peanut butter.',
    meal_type: 'snack',
    category: 'Snack',
    ingredients: [
      { name: 'celery', quantity: 3, unit: 'stalks' },
      { name: 'peanut butter', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Cut celery into sticks.',
      'Fill the groove with peanut butter.',
    ],
    tags: ['no cook', 'quick', 'budget friendly'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
  },
]);
