-- Add food emoji icons to catalog and categories for global icon resolution.

alter table public.food_categories
  add column if not exists icon text not null default '🍽️';

alter table public.food_catalog_items
  add column if not exists icon text not null default '🍽️';

update public.food_categories set icon = '🥕' where name = 'Vegetables';
update public.food_categories set icon = '🍎' where name = 'Fruits';
update public.food_categories set icon = '🥩' where name = 'Meat & Poultry';
update public.food_categories set icon = '🐟' where name = 'Fish & Seafood';
update public.food_categories set icon = '🥛' where name = 'Dairy & Eggs';
update public.food_categories set icon = '🍝' where name = 'Grains & Pasta';
update public.food_categories set icon = '🍞' where name = 'Bread & Bakery';
update public.food_categories set icon = '🫘' where name = 'Legumes & Beans';
update public.food_categories set icon = '🫙' where name = 'Canned & Jarred Goods';
update public.food_categories set icon = '🧊' where name = 'Frozen Food';
update public.food_categories set icon = '🫙' where name = 'Sauces & Condiments';
update public.food_categories set icon = '🫒' where name = 'Oils, Vinegars & Fats';
update public.food_categories set icon = '🧂' where name = 'Spices & Seasonings';
update public.food_categories set icon = '🍿' where name = 'Snacks';
update public.food_categories set icon = '🥤' where name = 'Drinks';
update public.food_categories set icon = '🧁' where name = 'Baking & Sweeteners';
update public.food_categories set icon = '🍱' where name = 'Prepared / Leftovers';

update public.food_catalog_items set icon = '🍅' where name_key = 'tomato';
update public.food_catalog_items set icon = '🧅' where name_key = 'onion';
update public.food_catalog_items set icon = '🧄' where name_key = 'garlic';
update public.food_catalog_items set icon = '🥕' where name_key = 'carrot';
update public.food_catalog_items set icon = '🍄' where name_key = 'mushrooms';
update public.food_catalog_items set icon = '🥬' where name_key = 'lettuce';
update public.food_catalog_items set icon = '🍌' where name_key = 'banana';
update public.food_catalog_items set icon = '🍎' where name_key = 'apple';
update public.food_catalog_items set icon = '🍋' where name_key = 'lemon';
update public.food_catalog_items set icon = '🥑' where name_key = 'avocado';
update public.food_catalog_items set icon = '🫐' where name_key = 'berries';
update public.food_catalog_items set icon = '🍗' where name_key = 'chicken breast';
update public.food_catalog_items set icon = '🥩' where name_key = 'beef';
update public.food_catalog_items set icon = '🥩' where name_key = 'pork';
update public.food_catalog_items set icon = '🦃' where name_key = 'turkey';
update public.food_catalog_items set icon = '🐟' where name_key = 'tuna';
update public.food_catalog_items set icon = '🐟' where name_key = 'salmon';
update public.food_catalog_items set icon = '🦐' where name_key = 'shrimp';
update public.food_catalog_items set icon = '🐟' where name_key = 'cod';
update public.food_catalog_items set icon = '🥛' where name_key = 'milk';
update public.food_catalog_items set icon = '🧀' where name_key = 'cheese';
update public.food_catalog_items set icon = '🥛' where name_key = 'yogurt';
update public.food_catalog_items set icon = '🧈' where name_key = 'butter';
update public.food_catalog_items set icon = '🥚' where name_key = 'eggs';
update public.food_catalog_items set icon = '🍚' where name_key = 'rice';
update public.food_catalog_items set icon = '🍝' where name_key = 'pasta';
update public.food_catalog_items set icon = '🌾' where name_key = 'couscous';
update public.food_catalog_items set icon = '🌾' where name_key = 'quinoa';
update public.food_catalog_items set icon = '🥣' where name_key = 'oats';
update public.food_catalog_items set icon = '🍞' where name_key = 'bread';
update public.food_catalog_items set icon = '🌯' where name_key = 'wraps';
update public.food_catalog_items set icon = '🫓' where name_key = 'pita';
update public.food_catalog_items set icon = '🌯' where name_key = 'tortillas';
update public.food_catalog_items set icon = '🫘' where name_key = 'lentils';
update public.food_catalog_items set icon = '🫘' where name_key = 'chickpeas';
update public.food_catalog_items set icon = '🫘' where name_key = 'black beans';
update public.food_catalog_items set icon = '🫛' where name_key = 'peas';
update public.food_catalog_items set icon = '🐟' where name_key = 'canned tuna';
update public.food_catalog_items set icon = '🍅' where name_key = 'tomato sauce';
update public.food_catalog_items set icon = '🫘' where name_key = 'canned beans';
update public.food_catalog_items set icon = '🫒' where name_key = 'olives';
update public.food_catalog_items set icon = '🥦' where name_key = 'frozen vegetables';
update public.food_catalog_items set icon = '🍗' where name_key = 'frozen chicken';
update public.food_catalog_items set icon = '🐟' where name_key = 'frozen fish';
update public.food_catalog_items set icon = '🍱' where name_key = 'frozen meals';
update public.food_catalog_items set icon = '🍅' where name_key = 'ketchup';
update public.food_catalog_items set icon = '🫙' where name_key = 'mayo';
update public.food_catalog_items set icon = '🫙' where name_key = 'soy sauce';
update public.food_catalog_items set icon = '🫙' where name_key = 'mustard';
update public.food_catalog_items set icon = '🫙' where name_key = 'pesto';
update public.food_catalog_items set icon = '🫒' where name_key = 'olive oil';
update public.food_catalog_items set icon = '🫒' where name_key = 'sunflower oil';
update public.food_catalog_items set icon = '🫙' where name_key = 'vinegar';
update public.food_catalog_items set icon = '🫒' where name_key = 'cooking spray';
update public.food_catalog_items set icon = '🧂' where name_key = 'salt';
update public.food_catalog_items set icon = '🌶️' where name_key = 'pepper';
update public.food_catalog_items set icon = '🌶️' where name_key = 'paprika';
update public.food_catalog_items set icon = '🌿' where name_key = 'oregano';
update public.food_catalog_items set icon = '🍛' where name_key = 'curry';
update public.food_catalog_items set icon = '🥜' where name_key = 'nuts';
update public.food_catalog_items set icon = '🍟' where name_key = 'chips';
update public.food_catalog_items set icon = '🍘' where name_key = 'crackers';
update public.food_catalog_items set icon = '🍫' where name_key = 'protein bars';
update public.food_catalog_items set icon = '💧' where name_key = 'water';
update public.food_catalog_items set icon = '🧃' where name_key = 'juice';
update public.food_catalog_items set icon = '🥤' where name_key = 'soda';
update public.food_catalog_items set icon = '☕' where name_key = 'coffee';
update public.food_catalog_items set icon = '🍵' where name_key = 'tea';
update public.food_catalog_items set icon = '🌾' where name_key = 'flour';
update public.food_catalog_items set icon = '🍬' where name_key = 'sugar';
update public.food_catalog_items set icon = '🍯' where name_key = 'honey';
update public.food_catalog_items set icon = '🧁' where name_key = 'baking powder';
update public.food_catalog_items set icon = '🍫' where name_key = 'chocolate';
update public.food_catalog_items set icon = '🍗' where name_key = 'cooked chicken';
update public.food_catalog_items set icon = '🍚' where name_key = 'cooked rice';
update public.food_catalog_items set icon = '🍲' where name_key = 'soup';
update public.food_catalog_items set icon = '🍱' where name_key = 'meal prep portions';
