-- PantryFlow: seed food-smart base recipes from base_recipes_food_waste_collection.json
-- Generated by scripts/generate-food-waste-recipe-seed.mjs

begin;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000001', null, 'Lemon Herb Chicken and Vegetable Traybake', 'A bright one-tray dinner with juicy chicken, crisp-edged potatoes and flexible vegetables. Ideal for using carrots, peppers or onions before they spoil; cooked leftovers can be used in wraps, salads or fried rice.', 15, 45, 4, array['meat', 'high-protein', 'one-pan', 'meal-prep', 'gluten-free', 'food-smart']::text[], array['Preheat the oven to 210°C, or 190°C fan. Cut the potatoes, carrots, pepper and onion into similar bite-size pieces.', 'Spread the vegetables on a large baking tray. Add 1 tablespoon of olive oil, half the oregano, half the paprika, salt and black pepper, then toss well.', 'Pat the chicken dry. Rub it with the remaining olive oil, oregano, paprika, garlic, lemon zest and a little salt and pepper.', 'Place the chicken among the vegetables and roast for 35 minutes.', 'Turn the vegetables, squeeze over the lemon juice and roast for another 10 minutes, or until the vegetables are tender and the chicken is fully cooked.', 'Rest for 5 minutes before serving. Cool any leftovers promptly and refrigerate in a covered container.']::text[], null, 'dinner', 'Chicken', 'easy', true, null, 'pending', 'Appetizing lemon herb chicken thigh traybake with golden baby potatoes, roasted carrots, red pepper and red onion, fresh lemon wedges and parsley, warm natural daylight, modern rustic ceramic plate, cream linen background, realistic editorial food photography, overhead three-quarter view, no text, no people', 1, 'cloudflare_r2', 520, 21, 145, 40, 9, 650, 45, 8, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000001', 'boneless skinless chicken thighs', 600, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000001', 'baby potatoes', 600, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000001', 'carrots', 2, 'pieces')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000001', 'red bell pepper', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000001', 'red onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000001', 'lemon', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000001', 'garlic', 3, 'cloves')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000001', 'olive oil', 2, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000001', 'dried oregano', 2, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000001-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000001', 'smoked paprika', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000002', null, 'Smoky Turkey and Bean Chili', 'A comforting one-pot chili with lean turkey, beans and vegetables. It freezes well, stretches a modest amount of meat across four portions and is excellent over rice, potatoes or in wraps.', 15, 35, 4, array['meat', 'high-protein', 'high-fiber', 'one-pot', 'freezer-friendly', 'meal-prep']::text[], array['Heat the olive oil in a large saucepan over medium heat. Add the onion, carrot and pepper, then cook for 6 to 8 minutes until softened.', 'Add the turkey mince and cook for 5 minutes, breaking it into small pieces, until no pink remains.', 'Stir in the garlic, smoked paprika, cumin and chili powder and cook for 30 seconds.', 'Add the chopped tomatoes, drained beans and stock. Bring to a gentle boil, then reduce the heat.', 'Simmer uncovered for 20 minutes, stirring occasionally, until thick and rich. Add a splash of water if it becomes too dry.', 'Season to taste and finish with lime juice. Divide into portions; cool promptly before refrigerating or freezing.']::text[], null, 'dinner', 'Turkey', 'easy', true, null, 'pending', 'Rich smoky turkey and red bean chili in a matte ceramic bowl, visible tomato, red pepper and beans, lime wedge, small spoonful of yogurt and coriander garnish, cozy natural light, cream tabletop, realistic premium food photography, three-quarter overhead view, no text, no people', 1, 'cloudflare_r2', 430, 12, 95, 38, 11, 720, 42, 11, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000002', 'lean turkey mince', 500, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000002', 'kidney beans, drained', 480, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000002', 'chopped tomatoes', 800, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000002', 'onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000002', 'carrot', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000002', 'red bell pepper', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000002', 'garlic', 2, 'cloves')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000002', 'low-sodium chicken stock', 250, 'ml')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000002', 'olive oil', 1, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000002', 'smoked paprika', 2, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000011', 'b1000000-0000-4000-8000-000000000002', 'ground cumin', 2, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000012', 'b1000000-0000-4000-8000-000000000002', 'mild chili powder', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000002-0000-4000-8000-000000000013', 'b1000000-0000-4000-8000-000000000002', 'lime', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000003', null, 'One-Pan Beef, Tomato and Spinach Orzo', 'A cozy all-in-one pasta with lean beef, tomato and spinach. The spinach can be replaced by any tender greens that need using, while grated carrot disappears into the sauce.', 10, 25, 4, array['meat', 'one-pan', 'family-friendly', 'high-protein', 'hidden-veg', 'meal-prep']::text[], array['Heat the olive oil in a wide, deep pan over medium-high heat. Add the beef and cook for 5 minutes, breaking it up, until browned.', 'Add the onion and grated carrot and cook for 5 minutes. Stir in the garlic and oregano for 30 seconds.', 'Add the orzo, chopped tomatoes and stock. Stir well and bring to a gentle simmer.', 'Cook uncovered for 10 to 12 minutes, stirring frequently so the orzo does not stick, until tender. Add small splashes of water if needed.', 'Fold in the spinach and cook for 2 minutes until wilted. Stir in half the Parmesan.', 'Season to taste and serve with the remaining Parmesan. Cool leftovers promptly in shallow containers.']::text[], null, 'dinner', 'Beef', 'easy', true, null, 'pending', 'Creamy beef tomato and spinach orzo in a shallow sage ceramic bowl, visible small pasta grains, lean minced beef, wilted spinach and grated parmesan, warm natural window light, cream background, inviting realistic editorial food photography, no text, no people', 1, 'cloudflare_r2', 520, 16, 85, 35, 10, 680, 58, 9, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000003', 'lean beef mince', 400, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000003', 'orzo', 280, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000003', 'chopped tomatoes', 400, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000003', 'low-sodium beef stock', 650, 'ml')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000003', 'baby spinach', 150, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000003', 'onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000003', 'carrot', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000003', 'garlic', 2, 'cloves')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000003', 'Parmesan cheese', 40, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000003', 'olive oil', 1, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000003-0000-4000-8000-000000000011', 'b1000000-0000-4000-8000-000000000003', 'dried oregano', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000004', null, 'Leftover Chicken Vegetable Fried Rice', 'A fast, flexible meal designed for safely chilled cooked rice and leftover chicken. Frozen vegetables make it practical, while fresh carrots or peppers can be added whenever they need using.', 10, 15, 4, array['meat', 'leftovers', 'quick', 'one-pan', 'food-smart', 'high-protein']::text[], array['Use cooked rice that was cooled promptly and refrigerated. Break up any clumps before starting.', 'Heat 1 tablespoon of oil in a large wok or frying pan over high heat. Add the beaten eggs, scramble briefly, then transfer to a plate.', 'Add the remaining oil, carrot and the white parts of the spring onions. Stir-fry for 2 minutes.', 'Add the frozen peas, cooked chicken and garlic. Stir-fry for another 2 to 3 minutes until piping hot.', 'Add the rice and stir-fry for 4 minutes, tossing frequently. Return the egg to the pan.', 'Add the soy sauce, sesame oil and green spring onion tops. Toss well and serve immediately with lime wedges.']::text[], null, 'lunch', 'Chicken', 'easy', true, null, 'pending', 'Colorful chicken vegetable fried rice in a dark shallow bowl, separate golden rice grains, tender chicken, peas, carrot, scrambled egg and spring onion, lime wedge, bright natural light, warm minimalist table styling, realistic food photography, no text, no people', 1, 'cloudflare_r2', 470, 13, 150, 35, 6, 780, 52, 6, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000004', 'cooked chilled rice', 600, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000004', 'cooked chicken', 300, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000004', 'eggs', 2, 'pieces')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000004', 'frozen peas', 150, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000004', 'carrot', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000004', 'spring onions', 4, 'pieces')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000004', 'garlic', 2, 'cloves')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000004', 'reduced-sodium soy sauce', 3, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000004', 'vegetable oil', 2, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000004', 'sesame oil', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000004-0000-4000-8000-000000000011', 'b1000000-0000-4000-8000-000000000004', 'lime', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000005', null, 'Turkey Meatballs in Tomato Spinach Sauce', 'Tender oven-baked turkey meatballs in a simple tomato sauce with spinach. Make a double batch for the freezer or serve leftovers in a sandwich, wrap or grain bowl.', 20, 30, 4, array['meat', 'high-protein', 'freezer-friendly', 'meal-prep', 'family-friendly', 'batch-cooking']::text[], array['Preheat the oven to 210°C, or 190°C fan. Line a baking tray with baking paper.', 'Mix the turkey, breadcrumbs, egg, half the garlic, half the oregano, half the Parmesan, salt and pepper. Shape into 16 meatballs without compacting the mixture too firmly.', 'Place the meatballs on the tray, brush with half the olive oil and bake for 15 minutes.', 'Meanwhile, heat the remaining oil in a large pan. Cook the onion for 5 minutes, then add the remaining garlic and oregano for 30 seconds.', 'Add the passata and simmer for 10 minutes. Add the baked meatballs and simmer gently for another 8 minutes, or until fully cooked.', 'Fold in the spinach until wilted. Serve with the remaining Parmesan and your choice of pasta, rice or crusty bread.']::text[], null, 'dinner', 'Turkey', 'easy', true, null, 'pending', 'Golden turkey meatballs in rich tomato spinach sauce in a cream ceramic serving bowl, parmesan and basil garnish, a little crusty bread at the side, warm inviting natural light, refined realistic food photography, no text, no people', 1, 'cloudflare_r2', 390, 15, 125, 42, 9, 690, 22, 5, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000005', 'lean turkey mince', 600, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000005', 'passata', 700, 'ml')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000005', 'baby spinach', 150, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000005', 'breadcrumbs', 60, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000005', 'egg', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000005', 'onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000005', 'garlic', 3, 'cloves')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000005', 'Parmesan cheese', 50, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000005', 'olive oil', 1, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000005-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000005', 'dried oregano', 2, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000006', null, 'Red Lentil, Sweet Potato and Spinach Curry', 'A creamy, deeply flavored vegetarian curry made mostly from pantry staples. It freezes well and turns soft sweet potato or wilting spinach into a generous, satisfying meal.', 10, 30, 4, array['vegetarian', 'vegan', 'high-fiber', 'one-pot', 'freezer-friendly', 'gluten-free']::text[], array['Heat the oil in a large saucepan over medium heat. Cook the onion for 5 minutes until soft.', 'Add the garlic, ginger, curry powder, cumin and turmeric. Stir for 30 seconds until fragrant.', 'Add the sweet potato, rinsed lentils, chopped tomatoes, coconut milk and stock. Stir and bring to a gentle boil.', 'Reduce the heat, cover loosely and simmer for 20 to 25 minutes, stirring occasionally, until the lentils and sweet potato are tender.', 'Add a splash of water if the curry becomes too thick. Fold in the spinach and cook for 2 minutes.', 'Season to taste, add the lime juice and serve. Cool extra portions promptly before refrigerating or freezing.']::text[], null, 'dinner', 'Vegetarian', 'easy', true, null, 'pending', 'Creamy red lentil sweet potato and spinach curry in a handmade beige bowl, vivid golden orange sauce, tender sweet potato cubes, wilted greens, lime and coriander garnish, warm natural light, minimalist cream background, realistic appetizing food photography, no text, no people', 1, 'cloudflare_r2', 430, 15, 0, 17, 11, 590, 58, 14, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000006', 'red lentils', 250, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000006', 'sweet potato', 500, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000006', 'chopped tomatoes', 400, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000006', 'light coconut milk', 400, 'ml')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000006', 'low-sodium vegetable stock', 400, 'ml')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000006', 'baby spinach', 150, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000006', 'onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000006', 'garlic', 3, 'cloves')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000006', 'fresh ginger', 20, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000006', 'mild curry powder', 2, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000011', 'b1000000-0000-4000-8000-000000000006', 'ground cumin', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000012', 'b1000000-0000-4000-8000-000000000006', 'ground turmeric', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000013', 'b1000000-0000-4000-8000-000000000006', 'olive oil', 1, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000006-0000-4000-8000-000000000014', 'b1000000-0000-4000-8000-000000000006', 'lime', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000007', null, 'Crispy Black Bean and Vegetable Quesadillas', 'Crisp tortillas filled with smoky beans, vegetables and melted cheese. A quick way to use half peppers, leftover corn, greens or herbs, and easy to customize for different households.', 15, 15, 4, array['vegetarian', 'quick', 'high-fiber', 'family-friendly', 'customizable', 'food-smart']::text[], array['Mash half the black beans with a fork, leaving the rest whole.', 'Heat the olive oil in a frying pan. Cook the onion and pepper for 5 minutes, then add the corn, cumin and smoked paprika for 2 minutes.', 'Stir in all the beans, lime juice and 2 tablespoons of water. Cook for 2 minutes, then season to taste.', 'Spread the filling over one half of each tortilla. Add the spinach and cheese, then fold closed.', 'Wipe the pan clean and cook the quesadillas in batches over medium heat for 2 to 3 minutes per side until crisp and the cheese has melted.', 'Cut into wedges and serve with yogurt, salsa or extra lime.']::text[], null, 'lunch', 'Vegetarian', 'easy', true, null, 'pending', 'Golden crisp black bean vegetable quesadilla wedges on a warm ceramic plate, visible melted cheddar, beans, corn, red pepper and spinach, lime wedge and fresh salsa, bright natural light, friendly modern food photography, cream background, no text, no people', 1, 'cloudflare_r2', 520, 20, 45, 22, 6, 800, 61, 14, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000007', 'large whole-wheat tortillas', 4, 'pieces')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000007', 'black beans, drained', 480, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000007', 'cheddar cheese', 160, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000007', 'red bell pepper', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000007', 'onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000007', 'sweetcorn', 150, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000007', 'baby spinach', 80, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000007', 'lime', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000007', 'olive oil', 1, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000007', 'ground cumin', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000007-0000-4000-8000-000000000011', 'b1000000-0000-4000-8000-000000000007', 'smoked paprika', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000008', null, 'Spinach, Mushroom and Potato Frittata', 'A satisfying oven frittata that rescues cooked potatoes, mushrooms and tender greens. It works for breakfast, lunch or dinner and tastes good warm or chilled.', 15, 25, 4, array['vegetarian', 'gluten-free', 'meal-prep', 'leftovers', 'high-protein', 'food-smart']::text[], array['Preheat the oven grill to medium-high. Beat the eggs with the milk, half the cheese, salt and pepper.', 'Heat the olive oil in a 24 cm oven-safe non-stick frying pan. Cook the onion and mushrooms for 6 to 8 minutes until golden and most moisture has evaporated.', 'Add the sliced cooked potatoes and spinach. Cook for 2 minutes until the spinach wilts.', 'Pour in the egg mixture and stir once to distribute the vegetables. Cook over low heat for 6 to 8 minutes until the edges are set but the top remains slightly wet.', 'Sprinkle over the remaining cheese and place under the grill for 3 to 5 minutes until puffed, golden and set in the center.', 'Rest for 5 minutes before slicing. Refrigerate cooled portions in a covered container.']::text[], null, 'breakfast', 'Vegetarian', 'easy', true, null, 'pending', 'Golden spinach mushroom and potato frittata sliced in an oven-safe skillet, visible mushrooms, greens and potato, small green salad beside it, soft morning daylight, warm cream and sage styling, realistic editorial food photography, no text, no people', 1, 'cloudflare_r2', 330, 20, 390, 24, 5, 500, 18, 4, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000008-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000008', 'eggs', 8, 'pieces')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000008-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000008', 'cooked potatoes', 300, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000008-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000008', 'mushrooms', 250, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000008-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000008', 'baby spinach', 120, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000008-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000008', 'onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000008-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000008', 'cheddar cheese', 100, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000008-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000008', 'milk', 80, 'ml')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000008-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000008', 'olive oil', 1, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000009', null, 'Mediterranean Chickpea and Spinach Stew', 'A bright tomato-based chickpea stew with lemon and spinach. It relies on inexpensive pantry staples and is forgiving enough for courgette, peppers or other vegetables that need using.', 10, 25, 4, array['vegetarian', 'vegan', 'high-fiber', 'one-pot', 'gluten-free', 'pantry-friendly']::text[], array['Heat the olive oil in a large saucepan over medium heat. Cook the onion, carrot and pepper for 6 to 8 minutes until soft.', 'Add the garlic, smoked paprika and cumin and cook for 30 seconds.', 'Add the chopped tomatoes, chickpeas and stock. Bring to a gentle boil, then reduce the heat.', 'Simmer uncovered for 15 minutes. Lightly crush some chickpeas against the side of the pan to thicken the stew.', 'Fold in the spinach and cook for 2 minutes until wilted.', 'Add the lemon zest and juice, season to taste and serve with parsley and whole-grain bread or couscous if desired.']::text[], null, 'lunch', 'Vegetarian', 'easy', true, null, 'pending', 'Mediterranean chickpea tomato and spinach stew in a rustic light ceramic bowl, visible chickpeas, red pepper, carrot and wilted greens, lemon and parsley garnish, sunny natural daylight, cream linen, realistic wholesome food photography, no text, no people', 1, 'cloudflare_r2', 360, 10, 0, 16, 12, 620, 50, 15, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000009', 'chickpeas, drained', 720, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000009', 'chopped tomatoes', 400, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000009', 'baby spinach', 150, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000009', 'red bell pepper', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000009', 'carrot', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000009', 'onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000009', 'garlic', 3, 'cloves')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000009', 'low-sodium vegetable stock', 300, 'ml')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000009', 'lemon', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000009', 'olive oil', 2, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000011', 'b1000000-0000-4000-8000-000000000009', 'smoked paprika', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000009-0000-4000-8000-000000000012', 'b1000000-0000-4000-8000-000000000009', 'ground cumin', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipes (id, user_id, title, description, prep_time_minutes, cook_time_minutes, portions, tags, instructions, rating, meal_type, category, difficulty, is_base_recipe, base_recipe_id, image_status, image_prompt, image_version, image_storage_provider, nutrition_calories, nutrition_fat_g, nutrition_cholesterol_mg, nutrition_protein_g, nutrition_sugar_g, nutrition_sodium_mg, nutrition_carbs_g, nutrition_fiber_g, nutrition_calculated_at)
values ('b1000000-0000-4000-8000-000000000010', null, 'Roasted Vegetable, Chickpea and Feta Couscous', 'A colorful, satisfying couscous bowl that makes almost any mix of roastable vegetables taste intentional. It is excellent warm or chilled and packs well for lunch the next day.', 15, 30, 4, array['vegetarian', 'meal-prep', 'high-fiber', 'lunchbox', 'customizable', 'food-smart']::text[], array['Preheat the oven to 220°C, or 200°C fan. Cut the courgette, pepper, carrots and onion into similar bite-size pieces.', 'Spread the vegetables and chickpeas over a large baking tray. Toss with the olive oil, cumin, smoked paprika, salt and pepper.', 'Roast for 25 to 30 minutes, turning once, until tender and browned at the edges.', 'Place the couscous in a heatproof bowl. Pour over the hot stock, cover and leave for 8 minutes, then fluff with a fork.', 'Mix the lemon zest, lemon juice and parsley through the couscous. Fold in the roasted vegetables and chickpeas.', 'Crumble over the feta and serve warm, or cool promptly for packed lunches.']::text[], null, 'lunch', 'Vegetarian', 'easy', true, null, 'pending', 'Colorful roasted vegetable chickpea and feta couscous in a wide cream bowl, fluffy grains, golden chickpeas, courgette, red pepper, carrot, red onion, feta and parsley, lemon wedge, bright natural daylight, elegant realistic food photography, no text, no people', 1, 'cloudflare_r2', 510, 18, 25, 20, 12, 670, 68, 13, null)
on conflict (id) do update set
  user_id = excluded.user_id,
  title = excluded.title,
  description = excluded.description,
  prep_time_minutes = excluded.prep_time_minutes,
  cook_time_minutes = excluded.cook_time_minutes,
  portions = excluded.portions,
  tags = excluded.tags,
  instructions = excluded.instructions,
  rating = excluded.rating,
  meal_type = excluded.meal_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  is_base_recipe = excluded.is_base_recipe,
  base_recipe_id = excluded.base_recipe_id,
  image_status = excluded.image_status,
  image_prompt = excluded.image_prompt,
  image_version = excluded.image_version,
  image_storage_provider = excluded.image_storage_provider,
  nutrition_calories = excluded.nutrition_calories,
  nutrition_fat_g = excluded.nutrition_fat_g,
  nutrition_cholesterol_mg = excluded.nutrition_cholesterol_mg,
  nutrition_protein_g = excluded.nutrition_protein_g,
  nutrition_sugar_g = excluded.nutrition_sugar_g,
  nutrition_sodium_mg = excluded.nutrition_sodium_mg,
  nutrition_carbs_g = excluded.nutrition_carbs_g,
  nutrition_fiber_g = excluded.nutrition_fiber_g,
  nutrition_calculated_at = excluded.nutrition_calculated_at;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000001', 'b1000000-0000-4000-8000-000000000010', 'whole-wheat couscous', 250, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000002', 'b1000000-0000-4000-8000-000000000010', 'chickpeas, drained', 480, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000003', 'b1000000-0000-4000-8000-000000000010', 'courgette', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000004', 'b1000000-0000-4000-8000-000000000010', 'red bell pepper', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000005', 'b1000000-0000-4000-8000-000000000010', 'carrots', 2, 'pieces')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000006', 'b1000000-0000-4000-8000-000000000010', 'red onion', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000007', 'b1000000-0000-4000-8000-000000000010', 'feta cheese', 150, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000008', 'b1000000-0000-4000-8000-000000000010', 'low-sodium vegetable stock', 300, 'ml')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000009', 'b1000000-0000-4000-8000-000000000010', 'lemon', 1, 'piece')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000010', 'b1000000-0000-4000-8000-000000000010', 'fresh parsley', 20, 'g')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000011', 'b1000000-0000-4000-8000-000000000010', 'olive oil', 2, 'tbsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000012', 'b1000000-0000-4000-8000-000000000010', 'ground cumin', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

insert into public.recipe_ingredients (id, recipe_id, name, quantity, unit)
values ('c1000010-0000-4000-8000-000000000013', 'b1000000-0000-4000-8000-000000000010', 'smoked paprika', 1, 'tsp')
on conflict (id) do update set
  recipe_id = excluded.recipe_id,
  name = excluded.name,
  quantity = excluded.quantity,
  unit = excluded.unit;

commit;
